package com.fuelflex.platform.reception.service.impl;
import java.math.*; import java.time.*; import java.util.*; import java.util.function.*; import java.util.stream.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import com.fuelflex.platform.common.exception.*; import com.fuelflex.platform.common.security.AuthorizationService; import com.fuelflex.platform.notification.service.NotificationService; import com.fuelflex.platform.notification.dto.request.CreateNotificationCommand; import com.fuelflex.platform.notification.entity.NotificationCategory; import com.fuelflex.platform.notification.entity.Notification; import com.fuelflex.platform.notification.repository.NotificationRepository; import com.fuelflex.platform.purchaseorder.entity.*; import com.fuelflex.platform.purchaseorder.model.PurchaseOrderStatus; import com.fuelflex.platform.purchaseorder.repository.PurchaseOrderRepository; import com.fuelflex.platform.product.entity.Product; import com.fuelflex.platform.reception.dto.ReceptionDtos.*; import com.fuelflex.platform.reception.entity.*; import com.fuelflex.platform.reception.model.*; import com.fuelflex.platform.reception.repository.*; import com.fuelflex.platform.reception.service.ReceptionService; import com.fuelflex.platform.station.service.StationAccessService; import com.fuelflex.platform.tank.entity.Tank; import com.fuelflex.platform.tank.repository.TankRepository; import com.fuelflex.platform.user.entity.User; import com.fuelflex.platform.user.repository.UserRepository; import lombok.RequiredArgsConstructor;
@Service @RequiredArgsConstructor @Transactional public class ReceptionServiceImpl implements ReceptionService {
 private final ReceptionRepository receptions; private final ReceptionItemRepository items; private final ReceptionTankAllocationRepository allocations; private final ReceptionStockMovementRepository stockMovements; private final ReceptionHistoryRepository history; private final ReceptionNumberRepository numbers; private final PurchaseOrderRepository orders; private final TankRepository tanks; private final StationAccessService stationAccess; private final AuthorizationService authorization; private final NotificationService notifications; private final NotificationRepository notificationRepository; private final UserRepository users;
 @Override @Transactional(readOnly=true) public Page<Response> managerList(Pageable p){User a=current();role(a,"MANAGER");return receptions.findByOrganizationIdAndCreatedById(org(a).getId(),a.getId(),p).map(this::response);}
 @Override @Transactional(readOnly=true) public Response managerGet(UUID id){User a=current();role(a,"MANAGER");Reception r=manager(id,a,false);return response(r);}
 @Override public Response create(ReceptionCreateRequest req){User a=current();role(a,"MANAGER");PurchaseOrder po=orderForCreate(req.purchaseOrderId(),a);Reception r=new Reception();r.setReceptionNumber("REC-"+OffsetDateTime.now().getYear()+"-"+String.format("%06d",numbers.nextValue()));r.setOrganization(org(a));r.setStation(po.getStation());r.setPurchaseOrder(po);r.setCreatedBy(a);applyHeader(r,req.deliveryNoteNumber(),req.deliveryDate(),req.generalObservation());replaceItems(r,req.items(),po,a);receptions.save(r);record(r,null,ReceptionStatus.DRAFT,ReceptionHistoryAction.RECEPTION_CREATED,a,null);notifySupervisors(r,a,"RECEPTION_CREATED",NotificationCategory.INFORMATION,"notifications:events.receptionCreated.title","notifications:events.receptionCreated.message");return response(r);}
 @Override public Response update(UUID id,ReceptionUpdateRequest req){User a=current();role(a,"MANAGER");Reception r=manager(id,a,true);if(r.getStatus()!=ReceptionStatus.DRAFT&&r.getStatus()!=ReceptionStatus.RETURNED_FOR_CORRECTION)throw new ConflictException("Cette réception n’est plus modifiable.");boolean correction=r.getStatus()==ReceptionStatus.RETURNED_FOR_CORRECTION;applyHeader(r,req.deliveryNoteNumber(),req.deliveryDate(),req.generalObservation());replaceItems(r,req.items(),r.getPurchaseOrder(),a);record(r,r.getStatus(),r.getStatus(),ReceptionHistoryAction.RECEPTION_UPDATED,a,null);notifySupervisors(r,a,correction?"RECEPTION_CORRECTED":"RECEPTION_UPDATED",NotificationCategory.INFORMATION,correction?"notifications:events.receptionCorrected.title":"notifications:events.receptionUpdated.title",correction?"notifications:events.receptionCorrected.message":"notifications:events.receptionUpdated.message");return response(r);}
 @Override public Response submit(UUID id,ReceptionSubmitRequest req){User a=current();role(a,"MANAGER");Reception r=manager(id,a,true);if(r.getStatus()!=ReceptionStatus.DRAFT&&r.getStatus()!=ReceptionStatus.RETURNED_FOR_CORRECTION)throw new ConflictException("Cette réception n’est pas soumettable.");lockOrder(r);List<ReceptionItem> currentItems=items.findByReceptionId(r.getId());recomputeBacklogs(currentItems);validateItems(r);boolean over=currentItems.stream().anyMatch(i->i.getDifferenceQuantity().signum()>0);boolean partial=!over&&currentItems.stream().anyMatch(i->i.getDifferenceQuantity().signum()<0);String comment=clean(req==null?null:req.comment());if(over&&comment==null)throw new BusinessException("Une justification est obligatoire en cas de surlivraison.");r.setSubmittedAt(OffsetDateTime.now());r.setSupervisorReviewedBy(null);r.setSupervisorReviewedAt(null);r.setSupervisorComment(null);if(over){move(r,ReceptionStatus.PENDING_SUPERVISOR_APPROVAL,ReceptionHistoryAction.RECEPTION_SUBMITTED,a,comment);notifySupervisors(r,a,"RECEPTION_OVERAGE_SUBMITTED",NotificationCategory.ACTION_REQUIRED,"notifications:events.receptionOverage.title","notifications:events.receptionOverage.message");}else{record(r,r.getStatus(),r.getStatus(),ReceptionHistoryAction.RECEPTION_SUBMITTED,a,comment);validateReception(r,a);notifySupervisors(r,a,partial?"RECEPTION_PARTIAL_VALIDATED":"RECEPTION_VALIDATED",NotificationCategory.INFORMATION,partial?"notifications:events.receptionPartial.title":"notifications:events.receptionValidated.title",partial?"notifications:events.receptionPartial.message":"notifications:events.receptionValidated.message");}return response(r);}
 @Override @Transactional(readOnly=true) public List<HistoryResponse> managerHistory(UUID id){User a=current();role(a,"MANAGER");return histories(manager(id,a,false));}
 @Override @Transactional(readOnly=true) public Page<Response> supervisorList(Pageable p){User a=current();role(a,"SUPERVISOR");return receptions.findByOrganizationId(org(a).getId(),p).map(this::response);}
 @Override @Transactional(readOnly=true) public Response supervisorGet(UUID id){User a=current();role(a,"SUPERVISOR");return response(supervisor(id,a,false));}
 @Override public Response approve(UUID id,SupervisorReceptionDecisionRequest req){User a=current();role(a,"SUPERVISOR");Reception r=supervisor(id,a,true);require(r,ReceptionStatus.PENDING_SUPERVISOR_APPROVAL);lockOrder(r);r.setSupervisorReviewedBy(a);r.setSupervisorReviewedAt(OffsetDateTime.now());r.setSupervisorComment(clean(req.comment()));move(r,ReceptionStatus.APPROVED,ReceptionHistoryAction.SUPERVISOR_APPROVED,a,r.getSupervisorComment());validateReception(r,a);resolveActionNotifications(r);return response(r);}
 @Override public Response returnForCorrection(UUID id,SupervisorReceptionDecisionRequest req){User a=current();role(a,"SUPERVISOR");Reception r=supervisor(id,a,true);require(r,ReceptionStatus.PENDING_SUPERVISOR_APPROVAL);String c=clean(req.comment());if(c==null)throw new BusinessException("Un motif est obligatoire.");r.setSupervisorReviewedBy(a);r.setSupervisorReviewedAt(OffsetDateTime.now());r.setSupervisorComment(c);move(r,ReceptionStatus.RETURNED_FOR_CORRECTION,ReceptionHistoryAction.RETURNED_FOR_CORRECTION,a,c);resolveActionNotifications(r);return response(r);}
 @Override public Response cancel(UUID id,SupervisorReceptionDecisionRequest req){User a=current();role(a,"SUPERVISOR");Reception r=supervisor(id,a,true);require(r,ReceptionStatus.PENDING_SUPERVISOR_APPROVAL);String c=clean(req.comment());if(c==null)throw new BusinessException("Un motif est obligatoire.");r.setSupervisorReviewedBy(a);r.setSupervisorReviewedAt(OffsetDateTime.now());r.setSupervisorComment(c);move(r,ReceptionStatus.CANCELLED,ReceptionHistoryAction.RECEPTION_CANCELLED,a,c);resolveActionNotifications(r);return response(r);}
 @Override @Transactional(readOnly=true) public List<HistoryResponse> supervisorHistory(UUID id){User a=current();role(a,"SUPERVISOR");return histories(supervisor(id,a,false));}
 private PurchaseOrder orderForCreate(UUID id,User a){PurchaseOrder po=orders.lockByIdAndOrganizationId(id,org(a).getId()).orElseThrow(()->new ResourceNotFoundException("Commande introuvable."));if(po.getStatus()!=PurchaseOrderStatus.AWAITING_RECEPTION&&po.getStatus()!=PurchaseOrderStatus.PARTIALLY_RECEIVED)throw new ConflictException("La commande n’est pas en attente de réception.");stationAccess.checkStationAccess(a,po.getStation().getId());return po;}
 private void refreshPurchaseOrderStatus(PurchaseOrder po){boolean complete=true;for(PurchaseOrderItem poi:po.getItems()){BigDecimal received=items.sumValidatedForPurchaseOrderItem(poi.getId());if(received==null)received=BigDecimal.ZERO;if(received.compareTo(poi.getQuantity())<0)complete=false;}po.setStatus(complete?PurchaseOrderStatus.RECEIVED:PurchaseOrderStatus.PARTIALLY_RECEIVED);}
 private void validateReception(Reception r,User actor){if(r.getStatus()==ReceptionStatus.VALIDATED)throw new ConflictException("Cette réception est déjà validée.");for(ReceptionItem item:items.findByReceptionId(r.getId())){for(ReceptionTankAllocation allocation:allocations.findByReceptionItemId(item.getId())){if(stockMovements.existsByAllocationId(allocation.getId()))throw new ConflictException("Le stock de cette réception a déjà été comptabilisé.");ReceptionStockMovement movement=new ReceptionStockMovement();movement.setReception(r);movement.setAllocation(allocation);movement.setStation(r.getStation());movement.setTank(allocation.getTank());movement.setProduct(item.getProduct());movement.setQuantity(allocation.getQuantity());movement.setCreatedBy(actor);stockMovements.save(movement);}}move(r,ReceptionStatus.VALIDATED,ReceptionHistoryAction.RECEPTION_VALIDATED,actor,null);refreshPurchaseOrderStatus(r.getPurchaseOrder());}
 private void lockOrder(Reception r){PurchaseOrder locked=orders.lockByIdAndOrganizationId(r.getPurchaseOrder().getId(),r.getOrganization().getId()).orElseThrow(()->new ResourceNotFoundException("Commande introuvable."));if(locked.getStatus()!=PurchaseOrderStatus.AWAITING_RECEPTION&&locked.getStatus()!=PurchaseOrderStatus.PARTIALLY_RECEIVED)throw new ConflictException("La commande n’est plus réceptionnable.");r.setPurchaseOrder(locked);}
 private void recomputeBacklogs(List<ReceptionItem> currentItems){for(ReceptionItem item:currentItems){BigDecimal previous=items.sumValidatedForPurchaseOrderItem(item.getPurchaseOrderItem().getId());if(previous==null)previous=BigDecimal.ZERO;BigDecimal backlog=item.getPurchaseOrderItem().getQuantity().subtract(previous).max(BigDecimal.ZERO);item.setOrderedQuantitySnapshot(item.getPurchaseOrderItem().getQuantity());item.setPreviouslyReceivedQuantity(previous);item.setBacklogBeforeReception(backlog);item.setDifferenceQuantity(item.getReceivedQuantity().subtract(backlog));}}
 private void resolveActionNotifications(Reception r){OffsetDateTime now=OffsetDateTime.now();for(Notification notification:notificationRepository.findByOrganizationIdAndResourceTypeAndResourceIdAndRequiresActionTrue(r.getOrganization().getId(),"RECEPTION",r.getId())){notification.setRequiresAction(false);notification.setCategory(NotificationCategory.INFORMATION);notification.setRead(true);notification.setReadAt(now);}}
 private void notifySupervisors(Reception r,User actor,String event,NotificationCategory category,String title,String message){for(User recipient:users.findEnabledByOrganizationIdAndRoleCode(r.getOrganization().getId(),"SUPERVISOR")){if(!stationAccess.canAccessStation(recipient,r.getStation().getId()))continue;notifications.create(CreateNotificationCommand.builder().recipientId(recipient.getId()).organizationId(r.getOrganization().getId()).stationId(r.getStation().getId()).actorId(actor.getId()).eventType(event).category(category).titleKey(title).messageKey(message).resourceType("RECEPTION").resourceId(r.getId()).requiresAction(category==NotificationCategory.ACTION_REQUIRED).build());}}
 private void applyHeader(Reception r,String note,OffsetDateTime date,String obs){r.setDeliveryNoteNumber(clean(note));r.setDeliveryDate(date);r.setGeneralObservation(clean(obs));}
 private void replaceItems(Reception r,List<ReceptionItemRequest> req,PurchaseOrder po,User a){if(req==null||req.isEmpty())throw new BusinessException("La réception doit contenir au moins un produit.");List<ReceptionTankAllocation> builtAllocations=new ArrayList<>();Map<UUID,PurchaseOrderItem> byId=po.getItems().stream().collect(Collectors.toMap(PurchaseOrderItem::getId,Function.identity()));Set<UUID> seen=new HashSet<>();List<ReceptionItem> built=new ArrayList<>();for(ReceptionItemRequest x:req){if(!seen.add(x.purchaseOrderItemId()))throw new BusinessException("Une ligne du bon ne peut apparaître qu’une fois.");PurchaseOrderItem poi=byId.get(x.purchaseOrderItemId());if(poi==null)throw new ResourceNotFoundException("Produit absent du bon de commande.");ReceptionItem i=new ReceptionItem();i.setReception(r);i.setPurchaseOrderItem(poi);i.setProduct(poi.getProduct());i.setOrderedQuantitySnapshot(poi.getQuantity());BigDecimal previous=items.sumValidatedForPurchaseOrderItem(poi.getId());if(previous==null)previous=BigDecimal.ZERO;i.setPreviouslyReceivedQuantity(previous);BigDecimal backlog=poi.getQuantity().subtract(previous);if(backlog.signum()<0)backlog=BigDecimal.ZERO;i.setBacklogBeforeReception(backlog);i.setReceivedQuantity(x.receivedQuantity());i.setPurchaseUnitPrice(x.purchaseUnitPrice());i.setCurrency(clean(x.currency()));i.setDifferenceQuantity(x.receivedQuantity().subtract(backlog));i.setObservation(clean(x.observation()));built.add(i);validateAllocations(i,x.allocations(),po,builtAllocations);}
 List<ReceptionItem> old=items.findByReceptionId(r.getId());for(ReceptionItem i:old)allocations.deleteAll(allocations.findByReceptionItemId(i.getId()));items.deleteAll(old);r.getPurchaseOrder().getItems().size();items.saveAll(built);allocations.saveAll(builtAllocations);}
 private void validateAllocations(ReceptionItem item,List<ReceptionTankAllocationRequest> req,PurchaseOrder po,List<ReceptionTankAllocation> target){if(req==null)return;Set<UUID> seen=new HashSet<>();for(ReceptionTankAllocationRequest x:req){if(!seen.add(x.tankId()))throw new BusinessException("Une citerne ne peut apparaître qu’une fois.");Tank tank=tanks.findByIdAndDepotStationId(x.tankId(),po.getStation().getId()).orElseThrow(()->new ResourceNotFoundException("Citerne introuvable pour cette station."));if(!tank.getProduct().getId().equals(item.getProduct().getId()))throw new BusinessException("La citerne n’accepte pas ce produit.");ReceptionTankAllocation a1=new ReceptionTankAllocation();a1.setReceptionItem(item);a1.setTank(tank);a1.setQuantity(x.quantity());target.add(a1);}}
 private void validateItems(Reception r){for(ReceptionItem i:items.findByReceptionId(r.getId())){if(i.getReceivedQuantity()==null||i.getReceivedQuantity().signum()<=0)throw new BusinessException("Les quantités réceptionnées doivent être positives.");if(i.getPurchaseUnitPrice()==null||i.getPurchaseUnitPrice().signum()<=0)throw new BusinessException("Le prix d’achat doit être strictement positif.");BigDecimal allocated=allocations.findByReceptionItemId(i.getId()).stream().map(ReceptionTankAllocation::getQuantity).reduce(BigDecimal.ZERO,BigDecimal::add);if(allocated.compareTo(i.getReceivedQuantity())!=0)throw new BusinessException("La quantité répartie dans les citernes doit être égale à la quantité reçue.");}}
 private void move(Reception r,ReceptionStatus to,ReceptionHistoryAction action,User a,String c){ReceptionStatus from=r.getStatus();r.setStatus(to);record(r,from,to,action,a,c);}
 private void record(Reception r,ReceptionStatus old,ReceptionStatus next,ReceptionHistoryAction action,User a,String c){ReceptionHistory h=new ReceptionHistory();h.setReception(r);h.setOldStatus(old);h.setNewStatus(next);h.setAction(action);h.setPerformedBy(a);h.setComment(c);history.save(h);}
 private Reception supervisor(UUID id,User a,boolean lock){Reception r=tenant(id,a,lock);if(!stationAccess.canAccessStation(a,r.getStation().getId()))throw missing();return r;}
 private Reception manager(UUID id,User a,boolean lock){Reception r=tenant(id,a,lock);if(!r.getCreatedBy().getId().equals(a.getId())||!stationAccess.canAccessStation(a,r.getStation().getId()))throw missing();return r;}
 private Reception tenant(UUID id,User a,boolean lock){return(lock?receptions.lockByIdAndOrganizationId(id,org(a).getId()):receptions.findByIdAndOrganizationId(id,org(a).getId())).orElseThrow(this::missing);}
 private void require(Reception r,ReceptionStatus s){if(r.getStatus()!=s)throw new ConflictException("Transition impossible depuis "+r.getStatus()+".");}
 private ReceptionItem item(UUID id){return items.findById(id).orElseThrow(()->new ResourceNotFoundException("Ligne de réception introuvable."));}
 private List<HistoryResponse> histories(Reception r){return history.findByReceptionIdOrderByPerformedAtAscIdAsc(r.getId()).stream().map(h->new HistoryResponse(h.getId(),h.getAction(),h.getOldStatus(),h.getNewStatus(),user(h.getPerformedBy()),h.getPerformedAt(),h.getComment())).toList();}
 private Response response(Reception r){List<ReceptionItem> ris=items.findByReceptionId(r.getId());return new Response(r.getId(),r.getReceptionNumber(),r.getPurchaseOrder().getId(),r.getPurchaseOrder().getOrderNumber(),r.getStation().getId(),r.getStation().getName(),r.getStatus(),r.getDeliveryNoteNumber(),r.getDeliveryDate(),r.getGeneralObservation(),user(r.getCreatedBy()),r.getCreatedAt(),r.getUpdatedAt(),r.getSubmittedAt(),user(r.getSupervisorReviewedBy()),r.getSupervisorReviewedAt(),r.getSupervisorComment(),ris.stream().map(i->new ItemResponse(i.getId(),i.getPurchaseOrderItem().getId(),i.getProduct().getId(),i.getProduct().getName(),i.getOrderedQuantitySnapshot(),i.getPreviouslyReceivedQuantity(),i.getBacklogBeforeReception(),i.getReceivedQuantity(),i.getPurchaseUnitPrice(),i.getCurrency(),i.getDifferenceQuantity(),i.getObservation(),allocations.findByReceptionItemId(i.getId()).stream().map(a->new AllocationResponse(a.getId(),a.getTank().getId(),a.getTank().getName(),a.getQuantity())).toList())).toList());}
 private UserSummary user(User u){return u==null?null:new UserSummary(u.getId(),u.getFirstName(),u.getLastName());} private String clean(String x){return x==null||x.isBlank()?null:x.trim();} private User current(){return authorization.getAuthenticatedUser();} private com.fuelflex.platform.organization.entity.Organization org(User a){if(a==null||a.getOrganization()==null)throw new ForbiddenException("Organisation requise.");return a.getOrganization();} private void role(User a,String c){if(a==null||!a.isEnabled()||a.getRoles().stream().noneMatch(r->r.isActive()&&r.getCode().equalsIgnoreCase(c)))throw new ForbiddenException("Rôle requis: "+c);} private ResourceNotFoundException missing(){return new ResourceNotFoundException("Réception introuvable.");}
}
