import { ArrowLeft, Edit3, RefreshCw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { Link, useParams } from "react-router-dom";
import ManagerLayout from "../../components/layout/ManagerLayout";
import { getReceptionPermissions } from "../../services/auth/permissionService";
import { getManagerReception, getManagerReceptionHistory } from "../../services/reception/receptionService";
import "./ManagerReceptions.css";
function date(v,l){return v?new Intl.DateTimeFormat(l,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—"}
const action={RECEPTION_CREATED:"created",RECEPTION_UPDATED:"updated",RECEPTION_SUBMITTED:"submitted",RETURNED_FOR_CORRECTION:"returned",SUPERVISOR_APPROVED:"approved",RECEPTION_CANCELLED:"cancelled",RECEPTION_VALIDATED:"validated"};
export default function ManagerReceptionDetailPage(){const permissions=getReceptionPermissions();const{id}=useParams();const{t,i18n}=useTranslation(["receptions","common"]);const locale=i18n.language==="en"?"en-US":"fr-FR";const[r,setR]=useState(null),[history,setHistory]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null);const load=useCallback(async()=>{setLoading(true);try{const[a,h]=await Promise.all([getManagerReception(id),getManagerReceptionHistory(id)]);setR(a);setHistory(h||[])}catch(e){setError(e)}finally{setLoading(false)}},[id]);
// This effect synchronizes the page with the protected API.
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{load()},[load]);const canEdit=permissions.canUpdate&&r&&["DRAFT","RETURNED_FOR_CORRECTION"].includes(r.status);return <ManagerLayout><main className="receptions-page"><Link className="receptions-link" to="/gerant/receptions"><ArrowLeft size={15}/> {t("receptions:form.back")}</Link>{loading?<div className="receptions-state">{t("receptions:form.loading")}</div>:error?<div className="receptions-state"><p>{error.message||t("receptions:errors.load")}</p><button className="receptions-secondary" type="button" onClick={load}><RefreshCw size={16}/>{t("common:actions.retry")}</button></div>:<><header className="receptions-header"><div><p className="receptions-eyebrow">{t("receptions:eyebrow")}</p><h1>{r.receptionNumber}</h1><p>{r.purchaseOrderNumber} · {r.stationName||"—"}</p></div><span className={"receptions-status receptions-status-"+r.status}>{t("receptions:statuses."+r.status,{defaultValue:r.status})}</span></header>{r.status==="PENDING_SUPERVISOR_APPROVAL"&&<div className="reception-alert partial">{t("receptions:form.pendingSupervisor")}</div>}{r.status==="RETURNED_FOR_CORRECTION"&&<div className="reception-alert over">{t("receptions:form.returnedTitle")} — {r.supervisorComment||""}</div>}<section className="receptions-order-card"><div><strong>{t("receptions:form.information")}</strong><p>{r.deliveryNoteNumber||"—"} · {date(r.deliveryDate,locale)}</p><p>{r.generalObservation||""}</p></div><div>{canEdit&&<Link className="receptions-secondary" to={"/gerant/receptions/nouvelle?id="+r.id}><Edit3 size={16}/>{t("receptions:form.edit")}</Link>}{canEdit&&permissions.canSubmit&&<Link className="receptions-primary" to={"/gerant/receptions/nouvelle?id="+r.id}>{t(r.status==="RETURNED_FOR_CORRECTION"?"receptions:form.resubmit":"receptions:form.submit")}</Link>}</div></section><section className="receptions-order-list">{(r.items||[]).map(item=><article className="receptions-order-card" key={item.id}><div><h3>{item.productName}</h3><p>{t("receptions:form.received")}: {item.receivedQuantity} · {t("receptions:form.price")}: {item.purchaseUnitPrice} {item.currency||""}</p><p>{t("receptions:form.backlog")}: {item.backlogBeforeReception} · {t("receptions:form.difference")}: {item.differenceQuantity}</p></div><div>{(item.allocations||[]).map(a=><small key={a.id}>{a.tankName||a.tankId}: {a.quantity}</small>)}</div></article>)}</section><section className="receptions-form-card"><h2>{t("receptions:history.title")}</h2>{history.length?history.map(event=><p key={event.id}><strong>{t("receptions:history."+(action[event.action]||"updated"))}</strong> · {date(event.performedAt,locale)} · {event.performedBy?event.performedBy.firstName+" "+event.performedBy.lastName:"—"}{event.comment?" — "+event.comment:""}</p>):<p>—</p>}</section></>}</main></ManagerLayout>}
