import { Plus, RefreshCw, ArrowRight } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";
import ManagerLayout from "../../components/layout/ManagerLayout";
import { getReceptionPermissions } from "../../services/auth/permissionService";
import { getManagerOrders } from "../../services/purchaseOrder/purchaseOrderService";
import { getManagerReceptionAvailability, getManagerReceptions } from "../../services/reception/receptionService";
import "./ManagerReceptions.css";
const available = ["AWAITING_RECEPTION", "PARTIALLY_RECEIVED"];
const groups = {available:["AWAITING_RECEPTION","PARTIALLY_RECEIVED"],inProgress:["DRAFT"],pending:["PENDING_SUPERVISOR_APPROVAL"],returned:["RETURNED_FOR_CORRECTION"],completed:["APPROVED","VALIDATED","CANCELLED"]};
function date(value,locale){return value?new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";}
export default function ManagerReceptionsPage(){const permissions=getReceptionPermissions();const {t,i18n}=useTranslation(["receptions","common"]);const locale=i18n.language==="en"?"en-US":"fr-FR";const [receipts,setReceipts]=useState({content:[]});const [orders,setOrders]=useState([]);const [tab,setTab]=useState("available");const [loading,setLoading]=useState(true);const [error,setError]=useState(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{const [r,o]=await Promise.all([getManagerReceptions({size:50}),getManagerOrders({size:100})]);setReceipts(r);const candidates=(o.content||[]).filter(x=>available.includes(x.status));const checks=await Promise.all(candidates.map(async order=>{try{await getManagerReceptionAvailability(order.id);return order}catch{return null}}));setOrders(checks.filter(Boolean));}catch(e){setError(e)}finally{setLoading(false)}},[]);
// This effect synchronizes the page with the protected API.
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{load()},[load]);const filtered=useMemo(()=>receipts.content.filter(r=>(groups[tab]||[]).includes(r.status)),[receipts,tab]);return <ManagerLayout><section className="receptions-page"><header className="receptions-header"><div><p className="receptions-eyebrow">{t("receptions:eyebrow")}</p><h1>{t("receptions:list.title")}</h1><p>{t("receptions:list.subtitle")}</p></div>{permissions.canCreate&&<Link className="receptions-primary" to="/gerant/receptions/nouvelle"><Plus size={17}/>{t("receptions:list.new")}</Link>}
</header><div className="receptions-tabs">{[["available","available"],["inProgress","inProgress"],["pending","pending"],["returned","returned"],["completed","completed"]].map(([key,label])=><button className={tab===key?"receptions-tab active":"receptions-tab"} type="button" onClick={()=>setTab(key)} key={key}>{t("receptions:list."+label)}</button>)}</div>{loading?<div className="receptions-state">{t("receptions:form.loading")}</div>:error?<div className="receptions-state"><p>{error.status===403?t("receptions:errors.forbidden"):t("receptions:errors.load")}</p><button className="receptions-secondary" type="button" onClick={load}><RefreshCw size={16}/>{t("common:actions.retry")}</button></div>:tab==="available"?<div className="receptions-order-list">{orders.length?orders.map(order=><article className="receptions-order-card" key={order.id}><div><h3>{order.orderNumber}</h3><p>{order.station?.name||"—"} · {order.supplier?.displayName||"Sans fournisseur"}</p><p>{(order.items||[]).map(i=>i.productName+" · "+i.quantity+" "+(i.unit||"")).join(" · ")}</p></div>{permissions.canCreate&&<Link className="receptions-primary" to={"/gerant/receptions/nouvelle?purchaseOrderId="+order.id}>{t("receptions:list.receive")}<ArrowRight size={16}/></Link>}</article>):<div className="receptions-empty">{t("receptions:list.noOrders")}</div>}</div>:filtered.length?<table className="receptions-table"><thead><tr><th>{t("receptions:list.order")}</th><th>{t("receptions:list.station")}</th><th>{t("receptions:list.status")}</th><th>{t("receptions:list.date")}</th><th/></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><strong>{item.receptionNumber}</strong><br/><small>{item.purchaseOrderNumber}</small></td><td>{item.stationName||"—"}</td><td><span className={"receptions-status receptions-status-"+item.status}>{t("receptions:statuses."+item.status,{defaultValue:item.status})}</span></td><td>{date(item.updatedAt||item.createdAt,locale)}</td><td><Link className="receptions-link" to={"/gerant/receptions/"+item.id}>{t("receptions:list.view")}</Link></td></tr>)}</tbody></table>:<div className="receptions-empty">{t("receptions:list.empty")}</div>}</section></ManagerLayout>}
