package com.fuelflex.platform.operations.controller;
import static com.fuelflex.platform.operations.dto.DailyOperationsDtos.*; import static com.fuelflex.platform.operations.dto.TankReturnDtos.*; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import com.fuelflex.platform.operations.service.DailyOperationsService; import com.fuelflex.platform.operations.service.TankReturnService; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor;
@RestController @RequestMapping("/api/v1") @RequiredArgsConstructor public class DailyOperationsController{private final DailyOperationsService service;private final TankReturnService tankReturns;
 @PostMapping("/manager/operational-days/{id}/expenses")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('MANAGER') and hasAuthority('daily-expense:create')")public ExpenseResponse expense(@PathVariable UUID id,@Valid @RequestBody ExpenseRequest r){return service.addExpense(id,r);}
 @GetMapping("/manager/operational-days/{id}/expenses")@PreAuthorize("hasAuthority('MANAGER') and hasAuthority('daily-expense:view')")public List<ExpenseResponse> expenses(@PathVariable UUID id){return service.expenses(id);}
 @PostMapping("/manager/operational-days/{id}/gauges")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('MANAGER') and hasAuthority('tank-gauge:create')")public GaugeResponse gauge(@PathVariable UUID id,@Valid @RequestBody GaugeRequest r){return service.addGauge(id,r);}
 @GetMapping("/manager/operational-days/{id}/gauges")@PreAuthorize("hasAuthority('MANAGER') and hasAuthority('tank-gauge:view')")public List<GaugeResponse> gauges(@PathVariable UUID id){return service.gauges(id);}
 @GetMapping("/manager/operational-days/{id}/reconciliations")@PreAuthorize("hasAuthority('MANAGER') and hasAuthority('reconciliation:view')")public List<ReconciliationResponse> managerRecs(@PathVariable UUID id){return service.reconciliations(id);}
 @GetMapping("/manager/operational-days/{id}/rjv")@PreAuthorize("hasAuthority('MANAGER') and hasAuthority('rjv:view')")public RjvResponse managerRjv(@PathVariable UUID id){return service.rjv(id);}
 @GetMapping("/supervisor/operational-days/{id}/reconciliations")@PreAuthorize("hasAuthority('SUPERVISOR') and hasAuthority('reconciliation:view')")public List<ReconciliationResponse> supervisorRecs(@PathVariable UUID id){return service.reconciliations(id);}
 @GetMapping("/supervisor/operational-days/{id}/rjv")@PreAuthorize("hasAuthority('SUPERVISOR') and hasAuthority('rjv:view')")public RjvResponse supervisorRjv(@PathVariable UUID id){return service.rjv(id);}
 @GetMapping("/supervisor/operational-days/{id}/expenses")@PreAuthorize("hasAuthority('SUPERVISOR') and hasAuthority('daily-expense:view')")public List<ExpenseResponse> supervisorExpenses(@PathVariable UUID id){return service.expenses(id);}
 @GetMapping("/supervisor/operational-days/{id}/gauges")@PreAuthorize("hasAuthority('SUPERVISOR') and hasAuthority('tank-gauge:view')")public List<GaugeResponse> supervisorGauges(@PathVariable UUID id){return service.gauges(id);}
 @PostMapping("/manager/shift-assignments/{id}/tank-returns")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('MANAGER') and hasAuthority('tank-return:create')")public Response createReturn(@PathVariable UUID id,@Valid @RequestBody CreateRequest r){return tankReturns.create(id,r);}
 @GetMapping("/manager/shift-assignments/{id}/tank-returns")@PreAuthorize("hasAuthority('MANAGER') and hasAuthority('tank-return:view')")public List<Response> managerReturnsByShift(@PathVariable UUID id){return tankReturns.byShift(id);}
 @GetMapping("/manager/operational-days/{id}/tank-returns")@PreAuthorize("hasAuthority('MANAGER') and hasAuthority('tank-return:view')")public List<Response> managerReturnsByDay(@PathVariable UUID id){return tankReturns.byDay(id);}
 @GetMapping("/supervisor/shift-assignments/{id}/tank-returns")@PreAuthorize("hasAuthority('SUPERVISOR') and hasAuthority('tank-return:view')")public List<Response> supervisorReturnsByShift(@PathVariable UUID id){return tankReturns.byShift(id);}
 @GetMapping("/supervisor/operational-days/{id}/tank-returns")@PreAuthorize("hasAuthority('SUPERVISOR') and hasAuthority('tank-return:view')")public List<Response> supervisorReturnsByDay(@PathVariable UUID id){return tankReturns.byDay(id);}}
