spring.application.name=FuelFlex Platform

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/fuelflex
spring.datasource.username=fuelflex_user
spring.datasource.password=fuelflex123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
spring.jpa.open-in-view=false

# ==================================================
# EMAIL / SMTP
# ==================================================

spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS:false}

spring.mail.default-encoding=UTF-8

# ==================================================
# JWT
# ==================================================

security.jwt.secret=${JWT_SECRET:FuelFlexPlatformLocalDevelopmentSecretKey2026Minimum32Characters}
security.jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:3600000}