spring.application.name=FuelFlex Platform

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/fuelflex
spring.datasource.username=fuelflex_user
spring.datasource.password=fuelflex123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
spring.jpa.open-in-view=false