package com.fuelflex.platform.sale.service;
import static com.fuelflex.platform.sale.dto.PosSaleDtos.*; import java.math.*; import java.time.OffsetDateTime; import java.util.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.fuelflex.platform.assignment.repository.UserStationAssignmentRepository; import com.fuelflex.platform.common.exception.*; import com.fuelflex.platform.common.security.AuthorizationService; import com.fuelflex.platform.creditcustomer.entity.CreditCustomer; import com.fuelflex.platform.creditcustomer.repository.CreditCustomerRepository; import com.fuelflex.platform.operations.entity.*; import com.fuelflex.platform.operations.repository.PumpShiftAssignmentRepository; import com.fuelflex.platform.operations.service.*; import com.fuelflex.platform.reception.repository.ReceptionStockBalanceRepository; import com.fuelflex.platform.role.entity.Role; import com.fuelflex.platform.sale.entity.*; import com.fuelflex.platform.sale.repository.*; import com.fuelflex.platform.station.service.StationAccessService; import com.fuelflex.platform.tank.entity.Tank; import com.fuelflex.platform.tank.repository.TankRepository; import com.fuelflex.platform.user.entity.User; import lombok.RequiredArgsConstructor;
@Service @RequiredArgsConstructor @Transactional public class PosFuelSaleServiceImpl implements PosFuelSaleService{
 private final AuthorizationService authorization;private final PumpShiftAssignmentRepository shifts;private final UserStationAssignmentRepository administrativeAssignments;private final PosConfigurationResolver resolver;private final TankRepository tanks;private final ReceptionStockBalanceRepository inboundStock;private final SaleStockMovementRepository outboundStock;private final FuelSaleRepository sales;private final SaleNumberRepository numbers;private final CreditCustomerRepository creditCustomers;private final StationAccessService stationAccess;private final ShiftReconciliationService reconciliation;private final SupervisorOperationalNotifier notifier;
 public SaleResponse create(CreateSaleRequest r){return createSale(r.quantity(),r.vehicleType(),r.licensePlate(),SaleType.CASH,null);}
 public SaleResponse createCredit(CreateCreditSaleRequest r){User a=authenticatedPumpAttendant();CreditCustomer c=creditCustomers.findByIdAndOrganizationId(r.creditCustomerId(),a.getOrganization().getId()).orElseThrow(()->new ResourceNotFoundException("Client crédit introuvable."));if(!c.isActive())throw new BusinessException("Le client crédit est inactif.");return createSale(a,r.quantity(),r.vehicleType(),r.licensePlate(),SaleType.CREDIT,c);}
 private SaleResponse createSale(BigDecimal q,VehicleType v,String plate,SaleType type,CreditCustomer customer){return createSale(authenticatedPumpAttendant(),q,v,plate,type,customer);}
 private SaleResponse createSale(User attendant,BigDecimal q,VehicleType vehicle,String plate,SaleType type,CreditCustomer customer){PumpShiftAssignment shift=shifts.lockOpenByPumpAttendantId(attendant.getId(),OperationalStatus.OPEN).orElseThrow(()->new BusinessException("Le pompiste n’est actuellement affecté à aucun poste ouvert."));validateAssignment(attendant,shift);ResolvedPosContext context=type==SaleType.CASH?resolver.resolve(shift):resolver.resolveCredit(shift);Tank tank=tanks.lockById(context.tank().getId()).orElseThrow(()->new ResourceNotFoundException("La cuve du contexte POS est introuvable."));BigDecimal quantity=quantity(q);String license=license(vehicle,plate);BigDecimal available=availableStock(tank.getId());if(quantity.compareTo(available)>0)throw new BusinessException("Stock insuffisant dans la cuve. Stock disponible: "+available.toPlainString()+" L.");BigDecimal price=context.unitPrice();BigDecimal total=quantity.multiply(price).setScale(3,RoundingMode.HALF_UP);
  FuelSale sale=new FuelSale();sale.setSaleNumber("SALE-"+OffsetDateTime.now().getYear()+"-"+String.format("%06d",numbers.nextValue()));sale.setOrganization(shift.getOperationalDay().getOrganization());sale.setStation(shift.getOperationalDay().getStation());sale.setOperationalDay(shift.getOperationalDay());sale.setShiftAssignment(shift);sale.setPumpAttendant(attendant);sale.setFuelMeter(context.fuelMeter());sale.setDispensingPoint(context.dispensingPoint());sale.setTank(tank);sale.setProduct(context.product());sale.setTariffCategory(context.tariffCategory());sale.setCreditCustomer(customer);sale.setSaleType(type);sale.setStatus(SaleStatus.EFFECTIVE);sale.setQuantity(quantity);sale.setUnitPrice(price);sale.setTotalAmount(total);sale.setVehicleType(vehicle);sale.setLicensePlate(license);sale.setSoldAt(OffsetDateTime.now());sale=sales.saveAndFlush(sale);movement(sale,StockMovementType.OUTBOUND);return response(sale,context.pump().getId(),context.pump().getName());}
 public SaleResponse reverse(UUID id,ReverseSaleRequest req){User actor=role("MANAGER");FuelSale sale=sales.lockByIdAndOrganizationId(id,actor.getOrganization().getId()).orElseThrow(()->new ResourceNotFoundException("Vente POS introuvable."));stationAccess.checkStationAccess(actor,sale.getStation().getId());if(sale.getOperationalDay().getStatus()!=OperationalStatus.OPEN)throw new ConflictException("Une vente d’une journée clôturée ne peut plus être annulée.");if(sale.getStatus()==SaleStatus.REVERSED)throw new ConflictException("Cette vente a déjà été annulée.");tanks.lockById(sale.getTank().getId()).orElseThrow(()->new ResourceNotFoundException("Cuve introuvable."));sale.setStatus(SaleStatus.REVERSED);sale.setReversedBy(actor);sale.setReversedAt(OffsetDateTime.now());sale.setReversalReason(req.reason().trim());movement(sale,StockMovementType.REVERSAL);sales.save(sale);if(sale.getShiftAssignment().getStatus()==OperationalStatus.CLOSED)reconciliation.calculate(sale.getShiftAssignment());notifier.inform(actor,sale.getStation(),"POS_SALE_REVERSED","FUEL_SALE",sale.getId());return response(sale);}
 @Transactional(readOnly=true)public List<SaleResponse> findCurrentOperationalDaySales(){User a=authenticatedPumpAttendant();ResolvedPosContext c=currentContext(a);return sales.findByPumpAttendantIdAndOperationalDayIdOrderBySoldAtDesc(a.getId(),c.assignment().getOperationalDay().getId()).stream().map(this::response).toList();}
 @Transactional(readOnly=true)public SaleResponse findById(UUID id){User a=authenticatedPumpAttendant();ResolvedPosContext c=currentContext(a);var d=c.assignment().getOperationalDay();return response(sales.findByIdAndPumpAttendantIdAndOperationalDayIdAndOrganizationIdAndStationId(id,a.getId(),d.getId(),d.getOrganization().getId(),d.getStation().getId()).orElseThrow(()->new ResourceNotFoundException("Vente POS introuvable.")));}
 private void movement(FuelSale sale,StockMovementType type){if(outboundStock.existsBySaleIdAndMovementType(sale.getId(),type))throw new ConflictException("Le mouvement stock de cette vente existe déjà.");SaleStockMovement m=new SaleStockMovement();m.setSale(sale);m.setMovementType(type);m.setStation(sale.getStation());m.setTank(sale.getTank());m.setProduct(sale.getProduct());m.setQuantity(sale.getQuantity());try{outboundStock.saveAndFlush(m);}catch(DataIntegrityViolationException e){throw new ConflictException("Le mouvement stock de cette vente existe déjà.");}}
 private ResolvedPosContext currentContext(User a){PumpShiftAssignment s=shifts.findFirstByPumpAttendantIdAndStatusOrderByOpenedAtDesc(a.getId(),OperationalStatus.OPEN).orElseThrow(()->new BusinessException("Le pompiste n’est actuellement affecté à aucun poste ouvert."));validateAssignment(a,s);return resolver.resolve(s);}
 private void validateAssignment(User a,PumpShiftAssignment s){if(!s.getPumpAttendant().getId().equals(a.getId()))throw new ForbiddenException("Cette affectation appartient à un autre pompiste.");if(s.getStatus()!=OperationalStatus.OPEN)throw new ConflictException("L’affectation pompiste est fermée.");if(s.getOperationalDay().getStatus()!=OperationalStatus.OPEN)throw new ConflictException("La journée opérationnelle est fermée.");if(!s.getOperationalDay().getOrganization().getId().equals(a.getOrganization().getId()))throw new ForbiddenException("L’affectation POS appartient à une autre organisation.");if(!administrativeAssignments.existsByUserIdAndStationIdAndOrganizationIdAndValidUntilIsNull(a.getId(),s.getOperationalDay().getStation().getId(),a.getOrganization().getId()))throw new ForbiddenException("Le pompiste n’est plus affecté administrativement à cette station.");}
 private BigDecimal availableStock(UUID tank){BigDecimal v=zero(inboundStock.sumInboundByTankId(tank)).subtract(zero(outboundStock.sumOutboundByTankId(tank))).setScale(3,RoundingMode.UNNECESSARY);if(v.signum()<0)throw new ConflictException("Le stock calculé de la cuve est négatif; la vente est bloquée.");return v;}private BigDecimal zero(BigDecimal v){return(v==null?BigDecimal.ZERO:v).setScale(3,RoundingMode.UNNECESSARY);}
 private BigDecimal quantity(BigDecimal v){if(v==null||v.signum()<=0)throw new BusinessException("La quantité vendue doit être strictement positive.");try{return v.setScale(3,RoundingMode.UNNECESSARY);}catch(ArithmeticException e){throw new BusinessException("La quantité vendue accepte au maximum trois décimales.");}}
 private String license(VehicleType type,String v){String n=v==null?null:v.trim().replaceAll("\\s+"," ").toUpperCase(Locale.ROOT);if(n!=null&&n.isBlank())n=null;if(type!=VehicleType.MOTORCYCLE&&n==null)throw new BusinessException("La plaque d’immatriculation est obligatoire pour ce type de véhicule.");return n;}
 private User authenticatedPumpAttendant(){return role("PUMP_ATTENDANT");}private User role(String code){User u=authorization.getAuthenticatedUser();if(u==null||!u.isEnabled()||u.getOrganization()==null||u.getRoles().stream().filter(Role::isActive).noneMatch(r->code.equalsIgnoreCase(r.getCode())))throw new ForbiddenException("Rôle requis: "+code);return u;}
 private SaleResponse response(FuelSale s){var p=s.getDispensingPoint();var pump=p==null?s.getFuelMeter().getPump():p.getPump();return response(s,pump.getId(),pump.getName());}
 private SaleResponse response(FuelSale s,UUID pumpId,String pumpName){return new SaleResponse(s.getId(),s.getSaleNumber(),s.getOrganization().getId(),new ReferenceSummary(s.getStation().getId(),s.getStation().getName()),s.getOperationalDay().getId(),s.getShiftAssignment().getId(),new PumpAttendantSummary(s.getPumpAttendant().getId(),s.getPumpAttendant().getFirstName(),s.getPumpAttendant().getLastName(),s.getPumpAttendant().getOperationalCode()),new ReferenceSummary(pumpId,pumpName),s.getDispensingPoint()==null?null:new ReferenceSummary(s.getDispensingPoint().getId(),s.getDispensingPoint().getName()),new ReferenceSummary(s.getFuelMeter().getId(),s.getFuelMeter().getName()),new ReferenceSummary(s.getTank().getId(),s.getTank().getName()),new ReferenceSummary(s.getProduct().getId(),s.getProduct().getName()),new ReferenceSummary(s.getTariffCategory().getId(),s.getTariffCategory().getName()),s.getSaleType(),s.getStatus(),s.getCreditCustomer()==null?null:new ReferenceSummary(s.getCreditCustomer().getId(),s.getCreditCustomer().getName()),s.getQuantity(),s.getUnitPrice(),s.getTotalAmount(),s.getVehicleType(),s.getLicensePlate(),s.getSoldAt(),s.getReversedAt(),s.getReversalReason());}
}
