package com.fuelflex.platform.operations.service;
import static com.fuelflex.platform.operations.dto.DailyOperationsDtos.*; import java.math.*; import java.util.*; import java.util.function.Function; import java.util.stream.Collectors; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.fuelflex.platform.common.exception.*; import com.fuelflex.platform.common.security.AuthorizationService; import com.fuelflex.platform.operations.entity.*; import com.fuelflex.platform.operations.repository.*; import com.fuelflex.platform.reception.repository.ReceptionStockBalanceRepository; import com.fuelflex.platform.role.entity.Role; import com.fuelflex.platform.sale.entity.*; import com.fuelflex.platform.sale.repository.*; import com.fuelflex.platform.station.service.StationAccessService; import com.fuelflex.platform.tank.entity.Tank; import com.fuelflex.platform.tank.repository.TankRepository; import com.fuelflex.platform.user.entity.User; import lombok.RequiredArgsConstructor;
@Service @RequiredArgsConstructor @Transactional public class DailyOperationsServiceImpl implements DailyOperationsService{
 private final AuthorizationService authorization;private final OperationalDayRepository days;private final DailyExpenseRepository expenseRepo;private final TankGaugeReadingRepository gaugeRepo;private final ShiftReconciliationRepository reconciliationRepo;private final FuelSaleRepository sales;private final TankRepository tanks;private final ReceptionStockBalanceRepository inbound;private final SaleStockMovementRepository outbound;private final StationAccessService access;private final SupervisorOperationalNotifier notifier;
 public ExpenseResponse addExpense(UUID dayId,ExpenseRequest r){User a=role("MANAGER");OperationalDay d=day(dayId,a);open(d);DailyExpense e=new DailyExpense();e.setOrganization(d.getOrganization());e.setStation(d.getStation());e.setOperationalDay(d);e.setLabel(clean(r.label()));e.setAmount(scale(r.amount()));e.setReference(clean(r.reference()));e.setComment(clean(r.comment()));e.setCreatedBy(a);e=expenseRepo.save(e);notifier.inform(a,d.getStation(),"DAILY_EXPENSE_RECORDED","DAILY_EXPENSE",e.getId());return expense(e);}
 @Transactional(readOnly=true)public List<ExpenseResponse> expenses(UUID id){User a=viewer();day(id,a);return expenseRepo.findByOperationalDayIdOrderByCreatedAtAsc(id).stream().map(this::expense).toList();}
 public GaugeResponse addGauge(UUID dayId,GaugeRequest r){User a=role("MANAGER");OperationalDay d=day(dayId,a);open(d);Tank t=tanks.findByIdAndDepotStationId(r.tankId(),d.getStation().getId()).orElseThrow(()->new ResourceNotFoundException("Cuve introuvable pour cette station."));if(gaugeRepo.existsByOperationalDayIdAndTankId(dayId,t.getId()))throw new ConflictException("La jauge de cette cuve est déjà enregistrée pour la journée.");BigDecimal theoretical=stock(t.getId());BigDecimal physical=scale(r.physicalStock());if(physical.compareTo(t.getMaximumLevelLiters())>0)throw new BusinessException("Le stock physique dépasse la capacité de la cuve.");TankGaugeReading g=new TankGaugeReading();g.setOrganization(d.getOrganization());g.setStation(d.getStation());g.setOperationalDay(d);g.setTank(t);g.setTheoreticalStock(theoretical);g.setPhysicalStock(physical);g.setStockVariance(scale(physical.subtract(theoretical)));g.setComment(clean(r.comment()));g.setRecordedBy(a);try{g=gaugeRepo.saveAndFlush(g);}catch(DataIntegrityViolationException e){throw new ConflictException("La jauge de cette cuve est déjà enregistrée pour la journée.");}notifier.inform(a,d.getStation(),"TANK_GAUGE_RECORDED","TANK_GAUGE",g.getId());return gauge(g);}
 @Transactional(readOnly=true)public List<GaugeResponse> gauges(UUID id){User a=viewer();day(id,a);return gaugeRepo.findByOperationalDayIdOrderByTankNameAsc(id).stream().map(this::gauge).toList();}
 @Transactional(readOnly=true)public List<ReconciliationResponse> reconciliations(UUID id){User a=viewer();day(id,a);return reconciliationRepo.findByShiftAssignmentOperationalDayIdOrderByShiftAssignmentOpenedAtAsc(id).stream().map(this::reconciliation).toList();}
 @Transactional(readOnly=true)public RjvResponse rjv(UUID id){User a=viewer();OperationalDay d=day(id,a);List<FuelSale> effective=sales.findByOperationalDayIdOrderBySoldAtAsc(id).stream().filter(s->s.getStatus()==SaleStatus.EFFECTIVE).toList();List<ShiftReconciliation> recs=reconciliationRepo.findByShiftAssignmentOperationalDayIdOrderByShiftAssignmentOpenedAtAsc(id);List<DailyExpense> expenses=expenseRepo.findByOperationalDayIdOrderByCreatedAtAsc(id);List<TankGaugeReading> gauges=gaugeRepo.findByOperationalDayIdOrderByTankNameAsc(id);BigDecimal cashV=sum(effective,s->s.getSaleType()==SaleType.CASH,s->s.getQuantity());BigDecimal creditV=sum(effective,s->s.getSaleType()==SaleType.CREDIT,s->s.getQuantity());BigDecimal cashA=sum(effective,s->s.getSaleType()==SaleType.CASH,s->s.getTotalAmount());BigDecimal creditA=sum(effective,s->s.getSaleType()==SaleType.CREDIT,s->s.getTotalAmount());BigDecimal metered=recs.stream().map(ShiftReconciliation::getMeteredVolume).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal expense=expenses.stream().map(DailyExpense::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal theoretical=gauges.stream().map(TankGaugeReading::getTheoreticalStock).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal physical=gauges.stream().map(TankGaugeReading::getPhysicalStock).reduce(BigDecimal.ZERO,BigDecimal::add);
  return new RjvResponse(id,d.getOrganization().getId(),d.getStation().getId(),d.getStation().getName(),d.getBusinessDate(),d.getStatus().name(),scale(cashV),scale(cashA),scale(creditV),scale(creditA),scale(cashV.add(creditV)),scale(cashA.add(creditA)),scale(metered),scale(metered.subtract(cashV).subtract(creditV)),scale(expense),scale(theoretical),scale(physical),scale(physical.subtract(theoretical)),aggregate(effective,s->s.getProduct().getId(),s->s.getProduct().getName()),aggregate(effective,s->s.getPumpAttendant().getId(),s->s.getPumpAttendant().getFirstName()+" "+s.getPumpAttendant().getLastName()),aggregate(effective,s->s.getFuelMeter().getId(),s->s.getFuelMeter().getName()),recs.stream().map(this::reconciliation).toList(),expenses.stream().map(this::expense).toList(),gauges.stream().map(g->new StockRow(g.getTank().getId(),g.getTank().getName(),g.getTank().getProduct().getId(),g.getTank().getProduct().getName(),g.getTheoreticalStock(),g.getPhysicalStock(),g.getStockVariance())).toList());}
 private List<AggregateRow> aggregate(List<FuelSale> list,Function<FuelSale,UUID> id,Function<FuelSale,String> name){return list.stream().collect(Collectors.groupingBy(id,LinkedHashMap::new,Collectors.toList())).entrySet().stream().map(e->{List<FuelSale>x=e.getValue();BigDecimal cv=sum(x,s->s.getSaleType()==SaleType.CASH,FuelSale::getQuantity),rv=sum(x,s->s.getSaleType()==SaleType.CREDIT,FuelSale::getQuantity),ca=sum(x,s->s.getSaleType()==SaleType.CASH,FuelSale::getTotalAmount),ra=sum(x,s->s.getSaleType()==SaleType.CREDIT,FuelSale::getTotalAmount);return new AggregateRow(e.getKey(),name.apply(x.getFirst()),scale(cv),scale(rv),scale(cv.add(rv)),scale(ca),scale(ra),scale(ca.add(ra)));}).toList();}
 private BigDecimal sum(List<FuelSale> list,java.util.function.Predicate<FuelSale> p,Function<FuelSale,BigDecimal> f){return list.stream().filter(p).map(f).reduce(BigDecimal.ZERO,BigDecimal::add);}private BigDecimal stock(UUID tank){BigDecimal v=zero(inbound.sumInboundByTankId(tank)).subtract(zero(outbound.sumOutboundByTankId(tank)));if(v.signum()<0)throw new ConflictException("Le stock théorique de la cuve est négatif.");return scale(v);}private BigDecimal zero(BigDecimal v){return v==null?BigDecimal.ZERO:v;}
 private OperationalDay day(UUID id,User a){OperationalDay d=days.findByIdAndOrganizationId(id,a.getOrganization().getId()).orElseThrow(()->new ResourceNotFoundException("Journée opérationnelle introuvable."));access.checkStationAccess(a,d.getStation().getId());return d;}private void open(OperationalDay d){if(d.getStatus()!=OperationalStatus.OPEN)throw new ConflictException("La journée opérationnelle est clôturée.");}
 private User viewer(){User a=authorization.getAuthenticatedUser();if(a==null||!a.isEnabled()||a.getOrganization()==null||a.getRoles().stream().filter(Role::isActive).noneMatch(r->Set.of("MANAGER","SUPERVISOR").contains(r.getCode())))throw new ForbiddenException("Accès opérationnel refusé.");return a;}private User role(String c){User a=viewer();if(a.getRoles().stream().filter(Role::isActive).noneMatch(r->c.equals(r.getCode())))throw new ForbiddenException("Rôle requis: "+c);return a;}
 private ExpenseResponse expense(DailyExpense e){return new ExpenseResponse(e.getId(),e.getLabel(),e.getAmount(),e.getReference(),e.getComment(),e.getCreatedBy().getId(),e.getCreatedAt());}private GaugeResponse gauge(TankGaugeReading g){return new GaugeResponse(g.getId(),g.getTank().getId(),g.getTank().getName(),g.getTheoreticalStock(),g.getPhysicalStock(),g.getStockVariance(),g.getRecordedBy().getId(),g.getRecordedAt(),g.getComment());}private ReconciliationResponse reconciliation(ShiftReconciliation r){var s=r.getShiftAssignment();return new ReconciliationResponse(r.getId(),s.getId(),s.getPumpAttendant().getId(),s.getPumpAttendant().getFirstName()+" "+s.getPumpAttendant().getLastName(),s.getFuelMeter().getId(),s.getFuelMeter().getName(),r.getOpeningIndex(),r.getClosingIndex(),r.getMeteredVolume(),r.getCashVolume(),r.getCreditVolume(),r.getTotalSoldVolume(),r.getVolumeVariance(),r.getCalculatedAt());}
 private String clean(String v){return v==null||v.isBlank()?null:v.trim().replaceAll("\\s+"," ");}private BigDecimal scale(BigDecimal v){return(v==null?BigDecimal.ZERO:v).setScale(3,RoundingMode.UNNECESSARY);}
}
