package com.fuelflex.platform.operations.service;

import static com.fuelflex.platform.operations.dto.DailyOperationsDtos.*;
import java.math.*;import java.util.*;import java.util.function.*;import java.util.stream.Collectors;
import org.springframework.dao.DataIntegrityViolationException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.fuelflex.platform.common.exception.*;import com.fuelflex.platform.common.security.AuthorizationService;
import com.fuelflex.platform.operations.entity.*;import com.fuelflex.platform.operations.repository.*;
import com.fuelflex.platform.reception.repository.ReceptionStockBalanceRepository;import com.fuelflex.platform.role.entity.Role;
import com.fuelflex.platform.sale.entity.*;import com.fuelflex.platform.sale.repository.*;import com.fuelflex.platform.station.service.StationAccessService;
import com.fuelflex.platform.tank.entity.Tank;import com.fuelflex.platform.tank.repository.TankRepository;import com.fuelflex.platform.user.entity.User;
import lombok.RequiredArgsConstructor;

@Service @RequiredArgsConstructor @Transactional
public class DailyOperationsServiceImpl implements DailyOperationsService {
 private final AuthorizationService authorization;private final OperationalDayRepository days;private final DailyExpenseRepository expenseRepo;private final TankGaugeReadingRepository gaugeRepo;private final ShiftReconciliationRepository reconciliationRepo;private final FuelSaleRepository sales;private final TankRepository tanks;private final ReceptionStockBalanceRepository inbound;private final SaleStockMovementRepository outbound;private final MeteredStockMovementRepository meteredMovements;private final TankReturnSourceMovementRepository returnSourceMovements;private final TankReturnRepository tankReturns;private final TankReturnStockMovementRepository returnMovements;private final OperationalDaySummaryRepository summaries;private final StationAccessService access;private final SupervisorOperationalNotifier notifier;

 public ExpenseResponse addExpense(UUID dayId,ExpenseRequest r){User a=role("MANAGER");OperationalDay d=day(dayId,a);open(d);DailyExpense e=new DailyExpense();e.setOrganization(d.getOrganization());e.setStation(d.getStation());e.setOperationalDay(d);e.setLabel(clean(r.label()));e.setAmount(scale(r.amount()));e.setReference(clean(r.reference()));e.setComment(clean(r.comment()));e.setCreatedBy(a);e=expenseRepo.save(e);notifier.inform(a,d.getStation(),"DAILY_EXPENSE_RECORDED","DAILY_EXPENSE",e.getId());return expense(e);}
 @Transactional(readOnly=true) public List<ExpenseResponse> expenses(UUID id){User a=viewer();day(id,a);return expenseRepo.findByOperationalDayIdOrderByCreatedAtAsc(id).stream().map(this::expense).toList();}
 public GaugeResponse addGauge(UUID dayId,GaugeRequest r){User a=role("MANAGER");OperationalDay d=day(dayId,a);open(d);Tank t=tanks.findByIdAndDepotStationId(r.tankId(),d.getStation().getId()).orElseThrow(()->new ResourceNotFoundException("Cuve introuvable pour cette station."));if(gaugeRepo.existsByOperationalDayIdAndTankId(dayId,t.getId()))throw new ConflictException("La jauge de cette cuve est déjà enregistrée pour la journée.");BigDecimal theoretical=stock(t.getId()),physical=scale(r.physicalStock());if(physical.compareTo(t.getMaximumLevelLiters())>0)throw new BusinessException("Le stock physique dépasse la capacité de la cuve.");TankGaugeReading g=new TankGaugeReading();g.setOrganization(d.getOrganization());g.setStation(d.getStation());g.setOperationalDay(d);g.setTank(t);g.setTheoreticalStock(theoretical);g.setPhysicalStock(physical);g.setStockVariance(scale(physical.subtract(theoretical)));g.setComment(clean(r.comment()));g.setRecordedBy(a);try{g=gaugeRepo.saveAndFlush(g);}catch(DataIntegrityViolationException e){throw new ConflictException("La jauge de cette cuve est déjà enregistrée pour la journée.");}notifier.inform(a,d.getStation(),"TANK_GAUGE_RECORDED","TANK_GAUGE",g.getId());return gauge(g);}
 @Transactional(readOnly=true) public List<GaugeResponse> gauges(UUID id){User a=viewer();day(id,a);return gaugeRepo.findByOperationalDayIdOrderByTankNameAsc(id).stream().map(this::gauge).toList();}
 @Transactional(readOnly=true) public List<ReconciliationResponse> reconciliations(UUID id){User a=viewer();day(id,a);return reconciliationRepo.findByShiftAssignmentOperationalDayIdOrderByShiftAssignmentOpenedAtAsc(id).stream().map(this::reconciliation).toList();}

 @Transactional(readOnly=true) public RjvResponse rjv(UUID id){
  User a=viewer();OperationalDay d=day(id,a);List<FuelSale> effective=sales.findByOperationalDayIdOrderBySoldAtAsc(id).stream().filter(x->x.getStatus()==SaleStatus.EFFECTIVE&&x.getShiftAssignment().getStatus()==OperationalStatus.OPEN).toList();List<ShiftReconciliation> recs=reconciliationRepo.findByShiftAssignmentOperationalDayIdOrderByShiftAssignmentOpenedAtAsc(id);List<DailyExpense> expenses=expenseRepo.findByOperationalDayIdOrderByCreatedAtAsc(id);List<TankGaugeReading> gauges=gaugeRepo.findByOperationalDayIdOrderByTankNameAsc(id);
  BigDecimal cashV=scale(recSum(recs,ShiftReconciliation::getCashVolume).add(saleSum(effective,x->x.getSaleType()==SaleType.CASH,FuelSale::getQuantity)));BigDecimal creditV=scale(recSum(recs,ShiftReconciliation::getCreditVolume).add(saleSum(effective,x->x.getSaleType()==SaleType.CREDIT,FuelSale::getQuantity)));BigDecimal cashA=scale(recSum(recs,ShiftReconciliation::getCashAmount).add(saleSum(effective,x->x.getSaleType()==SaleType.CASH,FuelSale::getTotalAmount)));BigDecimal creditA=scale(recSum(recs,ShiftReconciliation::getCreditAmount).add(saleSum(effective,x->x.getSaleType()==SaleType.CREDIT,FuelSale::getTotalAmount)));BigDecimal metered=recSum(recs,ShiftReconciliation::getMeteredVolume);BigDecimal returned=scale(recSum(recs,ShiftReconciliation::getTankReturnVolume).add(scale(tankReturns.sumOpenQuantityByDayId(id))));BigDecimal expenseA=expenses.stream().map(DailyExpense::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal theoretical=gauges.stream().map(TankGaugeReading::getTheoreticalStock).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal physical=gauges.stream().map(TankGaugeReading::getPhysicalStock).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal sold=scale(cashV.add(creditV));BigDecimal accounted=recSum(recs,ShiftReconciliation::getAccountedVolume),variance=recSum(recs,ShiftReconciliation::getVolumeVariance),expectedCash=scale(cashA),expectedNet=scale(cashA.subtract(expenseA));
  Optional<OperationalDaySummary> snapshot=d.getStatus()==OperationalStatus.CLOSED?summaries.findByOperationalDayId(id):Optional.empty();if(snapshot.isPresent()){OperationalDaySummary x=snapshot.get();cashV=x.getCashVolume();cashA=x.getCashAmount();creditV=x.getCreditVolume();creditA=x.getCreditAmount();returned=x.getTankReturnVolume();sold=x.getSoldVolume();metered=x.getMeteredVolume();accounted=x.getAccountedVolume();variance=x.getVolumeVariance();expenseA=x.getExpenseAmount();expectedCash=x.getExpectedCash();expectedNet=x.getExpectedNetCash();theoretical=x.getTheoreticalStock();physical=x.getPhysicalStock();}
  List<AggregateRow> byProduct=mergeAggregates(aggregateRecs(recs,x->x.getProduct().getId(),x->x.getProduct().getName()),aggregateSales(effective,x->x.getProduct().getId(),x->x.getProduct().getName()));List<AggregateRow> byAttendant=mergeAggregates(aggregateRecs(recs,x->x.getShiftAssignment().getPumpAttendant().getId(),x->x.getShiftAssignment().getPumpAttendant().getFirstName()+" "+x.getShiftAssignment().getPumpAttendant().getLastName()),aggregateSales(effective,x->x.getPumpAttendant().getId(),x->x.getPumpAttendant().getFirstName()+" "+x.getPumpAttendant().getLastName()));List<AggregateRow> byMeter=mergeAggregates(aggregateRecs(recs,x->x.getShiftAssignment().getFuelMeter().getId(),x->x.getShiftAssignment().getFuelMeter().getName()),aggregateSales(effective,x->x.getFuelMeter().getId(),x->x.getFuelMeter().getName()));
  return new RjvResponse(id,d.getOrganization().getId(),d.getStation().getId(),d.getStation().getName(),d.getBusinessDate(),d.getStatus().name(),scale(cashV),scale(cashA),scale(creditV),scale(creditA),scale(returned),scale(sold),scale(cashA.add(creditA)),scale(metered),scale(accounted),scale(variance),scale(expectedCash),scale(expenseA),scale(expenseA),scale(expectedNet),scale(theoretical),scale(physical),scale(physical.subtract(theoretical)),byProduct,byAttendant,byMeter,recs.stream().map(this::reconciliation).toList(),expenses.stream().map(this::expense).toList(),gauges.stream().map(g->new StockRow(g.getTank().getId(),g.getTank().getName(),g.getTank().getProduct().getId(),g.getTank().getProduct().getName(),g.getTheoreticalStock(),g.getPhysicalStock(),g.getStockVariance())).toList());
 }

 private List<AggregateRow> aggregateSales(List<FuelSale> list,Function<FuelSale,UUID> id,Function<FuelSale,String> name){return list.stream().collect(Collectors.groupingBy(id,LinkedHashMap::new,Collectors.toList())).entrySet().stream().map(e->{List<FuelSale>x=e.getValue();BigDecimal cv=saleSum(x,s->s.getSaleType()==SaleType.CASH,FuelSale::getQuantity),rv=saleSum(x,s->s.getSaleType()==SaleType.CREDIT,FuelSale::getQuantity),ca=saleSum(x,s->s.getSaleType()==SaleType.CASH,FuelSale::getTotalAmount),ra=saleSum(x,s->s.getSaleType()==SaleType.CREDIT,FuelSale::getTotalAmount);return new AggregateRow(e.getKey(),name.apply(x.getFirst()),cv,rv,scale(cv.add(rv)),ca,ra,scale(ca.add(ra)));}).toList();}
 private List<AggregateRow> aggregateRecs(List<ShiftReconciliation> list,Function<ShiftReconciliation,UUID> id,Function<ShiftReconciliation,String> name){return list.stream().collect(Collectors.groupingBy(id,LinkedHashMap::new,Collectors.toList())).entrySet().stream().map(e->{List<ShiftReconciliation>x=e.getValue();BigDecimal cv=recSum(x,ShiftReconciliation::getCashVolume),rv=recSum(x,ShiftReconciliation::getCreditVolume),ca=recSum(x,ShiftReconciliation::getCashAmount),ra=recSum(x,ShiftReconciliation::getCreditAmount);return new AggregateRow(e.getKey(),name.apply(x.getFirst()),cv,rv,scale(cv.add(rv)),ca,ra,scale(ca.add(ra)));}).toList();}
 private List<AggregateRow> mergeAggregates(List<AggregateRow> definitive,List<AggregateRow> provisional){Map<UUID,AggregateRow> merged=new LinkedHashMap<>();for(AggregateRow row:definitive)merged.put(row.id(),row);for(AggregateRow row:provisional)merged.merge(row.id(),row,(a,b)->new AggregateRow(a.id(),a.name(),scale(a.cashVolume().add(b.cashVolume())),scale(a.creditVolume().add(b.creditVolume())),scale(a.totalVolume().add(b.totalVolume())),scale(a.cashAmount().add(b.cashAmount())),scale(a.creditAmount().add(b.creditAmount())),scale(a.totalAmount().add(b.totalAmount()))));return List.copyOf(merged.values());}
 private BigDecimal saleSum(List<FuelSale> list,Predicate<FuelSale> p,Function<FuelSale,BigDecimal> f){return scale(list.stream().filter(p).map(f).reduce(BigDecimal.ZERO,BigDecimal::add));}private BigDecimal recSum(List<ShiftReconciliation> list,Function<ShiftReconciliation,BigDecimal> f){return scale(list.stream().map(f).reduce(BigDecimal.ZERO,BigDecimal::add));}
 private BigDecimal stock(UUID tank){BigDecimal v=zero(inbound.sumInboundByTankId(tank)).subtract(zero(outbound.sumOutboundByTankId(tank))).subtract(zero(meteredMovements.sumOutboundByTankId(tank))).subtract(zero(returnSourceMovements.sumOpenOutboundByTankId(tank))).add(zero(returnMovements.sumInboundByTankId(tank)));if(v.signum()<0)throw new ConflictException("Le stock théorique de la cuve est négatif.");return scale(v);}private BigDecimal zero(BigDecimal v){return v==null?BigDecimal.ZERO:v;}
 private OperationalDay day(UUID id,User a){OperationalDay d=days.findByIdAndOrganizationId(id,a.getOrganization().getId()).orElseThrow(()->new ResourceNotFoundException("Journée opérationnelle introuvable."));access.checkStationAccess(a,d.getStation().getId());return d;}private void open(OperationalDay d){if(d.getStatus()!=OperationalStatus.OPEN)throw new ConflictException("La journée opérationnelle est clôturée.");}
 private User viewer(){User a=authorization.getAuthenticatedUser();if(a==null||!a.isEnabled()||a.getOrganization()==null||a.getRoles().stream().filter(Role::isActive).noneMatch(r->Set.of("MANAGER","SUPERVISOR").contains(r.getCode())))throw new ForbiddenException("Accès opérationnel refusé.");return a;}private User role(String c){User a=viewer();if(a.getRoles().stream().filter(Role::isActive).noneMatch(r->c.equals(r.getCode())))throw new ForbiddenException("Rôle requis: "+c);return a;}
 private ExpenseResponse expense(DailyExpense e){return new ExpenseResponse(e.getId(),e.getLabel(),e.getAmount(),e.getReference(),e.getComment(),e.getCreatedBy().getId(),e.getCreatedAt());}private GaugeResponse gauge(TankGaugeReading g){return new GaugeResponse(g.getId(),g.getTank().getId(),g.getTank().getName(),g.getTheoreticalStock(),g.getPhysicalStock(),g.getStockVariance(),g.getRecordedBy().getId(),g.getRecordedAt(),g.getComment());}
 private ReconciliationResponse reconciliation(ShiftReconciliation r){var s=r.getShiftAssignment();var m=s.getFuelMeter();var point=m.getDispensingPoint();var pump=point==null?m.getPump():point.getPump();return new ReconciliationResponse(r.getId(),s.getId(),s.getPumpAttendant().getId(),s.getPumpAttendant().getFirstName()+" "+s.getPumpAttendant().getLastName(),m.getId(),m.getName(),pump.getId(),pump.getName(),r.getSourceTank().getId(),r.getSourceTank().getName(),r.getProduct().getId(),r.getProduct().getName(),r.getOpeningIndex(),r.getClosingIndex(),r.getMeteredVolume(),r.getCashVolume(),r.getCashUnitPrice(),r.getCashAmount(),r.getCreditVolume(),r.getCreditUnitPrice(),r.getCreditAmount(),r.getTankReturnVolume(),r.getTotalSoldVolume(),r.getTurnover(),r.getCashAmount(),r.getAccountedVolume(),r.getVolumeVariance(),r.getCalculatedAt());}
 private String clean(String v){return v==null||v.isBlank()?null:v.trim().replaceAll("\\s+"," ");}private BigDecimal scale(BigDecimal v){return(v==null?BigDecimal.ZERO:v).setScale(3,RoundingMode.UNNECESSARY);}
}
