package com.fuelflex.platform.operations.service;
import java.math.*; import java.time.OffsetDateTime; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import com.fuelflex.platform.common.exception.ConflictException; import com.fuelflex.platform.operations.entity.*; import com.fuelflex.platform.operations.repository.*; import com.fuelflex.platform.sale.entity.SaleType; import com.fuelflex.platform.sale.repository.FuelSaleRepository; import com.fuelflex.platform.tank.entity.Tank; import com.fuelflex.platform.tank.repository.TankRepository; import com.fuelflex.platform.user.entity.User; import lombok.RequiredArgsConstructor;
@Service @RequiredArgsConstructor @Transactional public class OperationalDayClosingService{
 private final PumpShiftAssignmentRepository shifts;private final ShiftReconciliationRepository reconciliations;private final TankGaugeReadingRepository gauges;private final TankRepository tanks;private final FuelSaleRepository sales;private final DailyExpenseRepository expenses;private final OperationalDaySummaryRepository summaries;private final SupervisorOperationalNotifier notifier;
 public OperationalDaySummary prepare(OperationalDay day,User actor){long open=shifts.countByOperationalDayIdAndStatus(day.getId(),OperationalStatus.OPEN);if(open>0)throw new ConflictException("Impossible de clôturer la journée : "+open+" affectation(s) restent ouvertes.");long shiftCount=shifts.countByOperationalDayId(day.getId());if(reconciliations.countByShiftAssignmentOperationalDayId(day.getId())!=shiftCount)throw new ConflictException("Tous les rapprochements compteur/ventes doivent être calculés avant la clôture.");List<Tank> active=tanks.findByDepotStationIdAndActiveTrueOrderByDisplayOrderAscNameAsc(day.getStation().getId());List<TankGaugeReading> readings=gauges.findByOperationalDayIdOrderByTankNameAsc(day.getId());Set<UUID> gauged=new HashSet<>();readings.forEach(g->gauged.add(g.getTank().getId()));List<String> missing=active.stream().filter(t->!gauged.contains(t.getId())).map(Tank::getName).toList();if(!missing.isEmpty())throw new ConflictException("Jauges manquantes pour les cuves: "+String.join(", ",missing)+".");
  BigDecimal cashV=s(sales.sumEffectiveQuantityByDayAndType(day.getId(),SaleType.CASH)),creditV=s(sales.sumEffectiveQuantityByDayAndType(day.getId(),SaleType.CREDIT));BigDecimal cashA=s(sales.sumEffectiveAmountByDayAndType(day.getId(),SaleType.CASH)),creditA=s(sales.sumEffectiveAmountByDayAndType(day.getId(),SaleType.CREDIT));BigDecimal metered=reconciliations.findByShiftAssignmentOperationalDayIdOrderByShiftAssignmentOpenedAtAsc(day.getId()).stream().map(ShiftReconciliation::getMeteredVolume).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal theoretical=readings.stream().map(TankGaugeReading::getTheoreticalStock).reduce(BigDecimal.ZERO,BigDecimal::add),physical=readings.stream().map(TankGaugeReading::getPhysicalStock).reduce(BigDecimal.ZERO,BigDecimal::add);
  OperationalDaySummary summary=new OperationalDaySummary();summary.setOperationalDay(day);summary.setCashVolume(cashV);summary.setCashAmount(cashA);summary.setCreditVolume(creditV);summary.setCreditAmount(creditA);summary.setMeteredVolume(s(metered));summary.setSoldVolume(s(cashV.add(creditV)));summary.setVolumeVariance(s(metered.subtract(cashV).subtract(creditV)));summary.setExpenseAmount(s(expenses.sumByDayId(day.getId())));summary.setTheoreticalStock(s(theoretical));summary.setPhysicalStock(s(physical));summary.setStockVariance(s(physical.subtract(theoretical)));summary.setClosedBy(actor);summary.setClosedAt(OffsetDateTime.now());summary=summaries.save(summary);notifier.inform(actor,day.getStation(),"OPERATIONAL_DAY_CLOSED","OPERATIONAL_DAY",day.getId());return summary;}
 private BigDecimal s(BigDecimal v){return(v==null?BigDecimal.ZERO:v).setScale(3,RoundingMode.UNNECESSARY);}
}
