package com.fuelflex.platform.operations.service;
import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.fuelflex.platform.assignment.repository.UserStationAssignmentRepository; import com.fuelflex.platform.common.exception.ForbiddenException; import com.fuelflex.platform.common.security.AuthorizationService;
import com.fuelflex.platform.dispensingpoint.entity.DispensingPoint; import com.fuelflex.platform.fuelmeter.entity.FuelMeter; import com.fuelflex.platform.operations.dto.OperationalDtos.PosOperationalContext; import com.fuelflex.platform.operations.entity.*; import com.fuelflex.platform.operations.repository.PumpShiftAssignmentRepository; import com.fuelflex.platform.pump.entity.Pump; import com.fuelflex.platform.role.entity.Role; import com.fuelflex.platform.user.entity.User; import lombok.RequiredArgsConstructor;
@Service @RequiredArgsConstructor @Transactional(readOnly=true)
public class PumpAttendantOperationalContextServiceImpl implements PumpAttendantOperationalContextService {
 private final AuthorizationService authorization; private final PumpShiftAssignmentRepository shifts; private final UserStationAssignmentRepository administrativeAssignments;
 public Optional<PosOperationalContext> currentContext(){User user=authorization.getAuthenticatedUser(); if(!user.isEnabled()||user.getRoles().stream().filter(Role::isActive).noneMatch(r->"PUMP_ATTENDANT".equalsIgnoreCase(r.getCode()))) throw new ForbiddenException("An active pump attendant account is required.");
  return shifts.findFirstByPumpAttendantIdAndStatusOrderByOpenedAtDesc(user.getId(),OperationalStatus.OPEN).filter(a->a.getOperationalDay().getStatus()==OperationalStatus.OPEN).filter(a->administrativeAssignments.existsByUserIdAndStationIdAndOrganizationIdAndValidUntilIsNull(user.getId(),a.getOperationalDay().getStation().getId(),user.getOrganization().getId())).map(a->{FuelMeter m=a.getFuelMeter();DispensingPoint point=m.getDispensingPoint();Pump pump=point==null?m.getPump():point.getPump();var d=a.getOperationalDay();return new PosOperationalContext(d.getId(),a.getId(),d.getOrganization().getId(),d.getStation().getId(),d.getStation().getName(),pump.getId(),pump.getName(),point==null?null:point.getId(),m.getId(),m.getName(),a.getOpeningIndex());}); }
}
