package com.fuelflex.platform.operations.service;
import java.math.*;import java.time.OffsetDateTime;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.fuelflex.platform.common.exception.*;import com.fuelflex.platform.operations.entity.*;import com.fuelflex.platform.operations.repository.*;import com.fuelflex.platform.sale.service.*;import lombok.RequiredArgsConstructor;
@Service @RequiredArgsConstructor @Transactional public class ShiftReconciliationService{
 private final ShiftReconciliationRepository reconciliations;private final TankReturnRepository tankReturns;private final PosConfigurationResolver pricing;
 public ShiftReconciliation calculate(PumpShiftAssignment shift,BigDecimal requestedCredit){
  if(shift.getClosingIndex()==null||shift.getOpeningIndex()==null)throw new BusinessException("Les index de l’affectation sont requis pour le rapprochement.");
  BigDecimal metered=s(shift.getClosingIndex().subtract(shift.getOpeningIndex()));BigDecimal returned=s(tankReturns.sumQuantityByShiftId(shift.getId()));BigDecimal credit=s(requestedCredit);
  if(returned.signum()<0)throw new BusinessException("La quantité remise en cuve ne peut pas être négative.");if(returned.compareTo(metered)>0)throw new BusinessException("La quantité remise en cuve dépasse la sortie compteur.");
  BigDecimal saleable=s(metered.subtract(returned));if(credit.signum()<0)throw new BusinessException("La quantité crédit ne peut pas être négative.");if(credit.compareTo(saleable)>0)throw new BusinessException("La quantité crédit dépasse le volume commercialisable de "+saleable.toPlainString()+" L.");
  BigDecimal cash=s(saleable.subtract(credit));ResolvedPosContext cashContext=pricing.resolve(shift),creditContext=pricing.resolveCredit(shift);if(!cashContext.tank().getId().equals(creditContext.tank().getId())||!cashContext.product().getId().equals(creditContext.product().getId()))throw new ConflictException("Les tarifs CASH et CREDIT ne résolvent pas la même configuration physique.");
  BigDecimal cashAmount=amount(cash,cashContext.unitPrice()),creditAmount=amount(credit,creditContext.unitPrice()),turnover=amount(cashAmount.add(creditAmount));
  ShiftReconciliation r=reconciliations.findByShiftAssignmentId(shift.getId()).orElseGet(ShiftReconciliation::new);r.setShiftAssignment(shift);r.setOpeningIndex(s(shift.getOpeningIndex()));r.setClosingIndex(s(shift.getClosingIndex()));r.setMeteredVolume(metered);r.setCashVolume(cash);r.setCreditVolume(credit);r.setTankReturnVolume(returned);r.setTotalSoldVolume(s(cash.add(credit)));r.setAccountedVolume(s(cash.add(credit).add(returned)));r.setVolumeVariance(s(metered.subtract(r.getAccountedVolume())));r.setSourceTank(cashContext.tank());r.setProduct(cashContext.product());r.setCashUnitPrice(s(cashContext.unitPrice()));r.setCreditUnitPrice(s(creditContext.unitPrice()));r.setCashAmount(cashAmount);r.setCreditAmount(creditAmount);r.setTurnover(turnover);r.setCalculatedAt(OffsetDateTime.now());return reconciliations.save(r);
 }
 /** A post-close POS reversal remains audited but cannot rewrite the definitive manager closure. */
 public ShiftReconciliation calculate(PumpShiftAssignment shift){return reconciliations.findByShiftAssignmentId(shift.getId()).orElseThrow(()->new ConflictException("Le rapprochement définitif de l’affectation est introuvable."));}
 private BigDecimal s(BigDecimal v){if(v==null)throw new BusinessException("La quantité crédit est requise.");try{return v.setScale(3,RoundingMode.UNNECESSARY);}catch(ArithmeticException e){throw new BusinessException("Les volumes acceptent au maximum trois décimales.");}}
 private BigDecimal amount(BigDecimal value){return value.setScale(3,RoundingMode.HALF_UP);}private BigDecimal amount(BigDecimal quantity,BigDecimal price){return quantity.multiply(price).setScale(3,RoundingMode.HALF_UP);}
}
