package com.fuelflex.platform.operations.blocktwo;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import java.math.*;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;
import com.fuelflex.platform.common.security.AuthorizationService;import com.fuelflex.platform.depot.entity.Depot;import com.fuelflex.platform.operations.dto.DailyOperationsDtos.*;import com.fuelflex.platform.operations.entity.*;import com.fuelflex.platform.operations.repository.*;import com.fuelflex.platform.operations.service.*;import com.fuelflex.platform.organization.entity.Organization;import com.fuelflex.platform.reception.repository.ReceptionStockBalanceRepository;import com.fuelflex.platform.role.entity.Role;import com.fuelflex.platform.sale.repository.*;import com.fuelflex.platform.station.entity.Station;import com.fuelflex.platform.station.service.StationAccessService;import com.fuelflex.platform.tank.entity.Tank;import com.fuelflex.platform.tank.repository.TankRepository;import com.fuelflex.platform.user.entity.User;
@ExtendWith(MockitoExtension.class)class DailyOperationsServiceTest{
 @Mock AuthorizationService auth;@Mock OperationalDayRepository days;@Mock DailyExpenseRepository expenses;@Mock TankGaugeReadingRepository gauges;@Mock ShiftReconciliationRepository recs;@Mock FuelSaleRepository sales;@Mock TankRepository tanks;@Mock ReceptionStockBalanceRepository inbound;@Mock SaleStockMovementRepository outbound;@Mock StationAccessService access;@Mock SupervisorOperationalNotifier notifier;DailyOperationsServiceImpl service;User manager;OperationalDay day;Tank tank;
 @BeforeEach void setup(){service=new DailyOperationsServiceImpl(auth,days,expenses,gauges,recs,sales,tanks,inbound,outbound,access,notifier);Organization org=new Organization();org.setId(UUID.randomUUID());Station station=new Station();station.setId(UUID.randomUUID());station.setName("S");station.setOrganization(org);manager=user(org,"MANAGER");day=new OperationalDay();day.setId(UUID.randomUUID());day.setOrganization(org);day.setStation(station);day.setStatus(OperationalStatus.OPEN);Depot depot=new Depot();depot.setStation(station);tank=new Tank();tank.setId(UUID.randomUUID());tank.setName("T");tank.setDepot(depot);tank.setMaximumLevelLiters(new BigDecimal("2000.000"));when(auth.getAuthenticatedUser()).thenReturn(manager);when(days.findByIdAndOrganizationId(day.getId(),org.getId())).thenReturn(Optional.of(day));}
 @Test void recordsExpenseInAuthenticatedScope(){when(expenses.save(any())).thenAnswer(i->{DailyExpense e=i.getArgument(0);e.setId(UUID.randomUUID());return e;});ExpenseResponse r=service.addExpense(day.getId(),new ExpenseRequest("Transport",new BigDecimal("25.000"),null,null));assertThat(r.amount()).isEqualByComparingTo("25.000");verify(notifier).inform(eq(manager),eq(day.getStation()),eq("DAILY_EXPENSE_RECORDED"),any(),any());}
 @Test void gaugeKeepsTheoreticalPhysicalAndVarianceSeparate(){when(tanks.findByIdAndDepotStationId(tank.getId(),day.getStation().getId())).thenReturn(Optional.of(tank));when(inbound.sumInboundByTankId(tank.getId())).thenReturn(new BigDecimal("1000.000"));when(outbound.sumOutboundByTankId(tank.getId())).thenReturn(new BigDecimal("100.000"));when(gauges.saveAndFlush(any())).thenAnswer(i->{TankGaugeReading g=i.getArgument(0);g.setId(UUID.randomUUID());return g;});GaugeResponse r=service.addGauge(day.getId(),new GaugeRequest(tank.getId(),new BigDecimal("895.000"),null));assertThat(r.theoreticalStock()).isEqualByComparingTo("900.000");assertThat(r.physicalStock()).isEqualByComparingTo("895.000");assertThat(r.stockVariance()).isEqualByComparingTo("-5.000");}
 @Test void rjvAggregatesCashCreditExpensesMeterAndStock(){
  com.fuelflex.platform.product.entity.Product product=new com.fuelflex.platform.product.entity.Product();product.setId(UUID.randomUUID());product.setName("Diesel");com.fuelflex.platform.fuelmeter.entity.FuelMeter meter=new com.fuelflex.platform.fuelmeter.entity.FuelMeter();meter.setId(UUID.randomUUID());meter.setName("M1");
  com.fuelflex.platform.sale.entity.FuelSale cash=sale(product,meter,com.fuelflex.platform.sale.entity.SaleType.CASH,"100","250");com.fuelflex.platform.sale.entity.FuelSale credit=sale(product,meter,com.fuelflex.platform.sale.entity.SaleType.CREDIT,"50","125");when(sales.findByOperationalDayIdOrderBySoldAtAsc(day.getId())).thenReturn(List.of(cash,credit));when(recs.findByShiftAssignmentOperationalDayIdOrderByShiftAssignmentOpenedAtAsc(day.getId())).thenReturn(List.of());when(expenses.findByOperationalDayIdOrderByCreatedAtAsc(day.getId())).thenReturn(List.of());when(gauges.findByOperationalDayIdOrderByTankNameAsc(day.getId())).thenReturn(List.of());
  RjvResponse r=service.rjv(day.getId());assertThat(r.cashVolume()).isEqualByComparingTo("100.000");assertThat(r.creditVolume()).isEqualByComparingTo("50.000");assertThat(r.totalSalesAmount()).isEqualByComparingTo("375.000");assertThat(r.byProduct()).hasSize(1);
 }
 private com.fuelflex.platform.sale.entity.FuelSale sale(com.fuelflex.platform.product.entity.Product p,com.fuelflex.platform.fuelmeter.entity.FuelMeter m,com.fuelflex.platform.sale.entity.SaleType type,String q,String amount){com.fuelflex.platform.sale.entity.FuelSale s=new com.fuelflex.platform.sale.entity.FuelSale();s.setSaleType(type);s.setStatus(com.fuelflex.platform.sale.entity.SaleStatus.EFFECTIVE);s.setQuantity(new BigDecimal(q));s.setTotalAmount(new BigDecimal(amount));s.setProduct(p);s.setFuelMeter(m);s.setPumpAttendant(manager);return s;}

 private User user(Organization o,String c){Role r=new Role();r.setCode(c);r.setActive(true);User u=new User();u.setId(UUID.randomUUID());u.setOrganization(o);u.setEnabled(true);u.setRoles(Set.of(r));return u;}
}
