package com.fuelflex.platform.operations.blocktwo;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import java.math.*;import java.nio.file.*;import java.util.*;import org.junit.jupiter.api.Test;
import com.fuelflex.platform.common.exception.ConflictException;import com.fuelflex.platform.operations.entity.*;import com.fuelflex.platform.operations.repository.MeteredStockMovementRepository;import com.fuelflex.platform.operations.service.*;import com.fuelflex.platform.product.entity.Product;import com.fuelflex.platform.station.entity.Station;import com.fuelflex.platform.tank.entity.Tank;import com.fuelflex.platform.user.entity.User;
class MeteredPhysicalStockTest{
 @Test void scenario1Initial10000Metered1000Leaves9000(){assertThat(stock("10000","1000","0")).isEqualByComparingTo("9000");}
 @Test void scenario2ReturnToSameTankLeaves9050(){assertThat(stock("10000","1000","50")).isEqualByComparingTo("9050");assertThat(reconciliation("1000","750","200","50")).isZero();}
 @Test void scenario3ReturnToOtherTankLeavesA9000AndB5050(){assertThat(stock("10000","1000","0")).isEqualByComparingTo("9000");assertThat(stock("5000","0","50")).isEqualByComparingTo("5050");assertThat(stock("15000","1000","50")).isEqualByComparingTo("14050");}
 @Test void cashCreditAndReturnKeepPhysicalAndCommercialTotalsSeparate(){assertThat(finalStock("100","20")).isEqualByComparingTo("-80");assertThat(new BigDecimal("50").add(new BigDecimal("30"))).isEqualByComparingTo("80");assertThat(reconciliation("100","50","30","20")).isZero();}
 @Test void varianceDoesNotInventSaleOrChangeMeteredOutbound(){assertThat(finalStock("100","20")).isEqualByComparingTo("-80");assertThat(reconciliation("100","75","0","20")).isEqualByComparingTo("5");}
 @Test void openShiftUsesSalesButClosedShiftUsesMeteredMovementWithoutDoubleCounting()throws Exception{String repository=Files.readString(Path.of("src/main/java/com/fuelflex/platform/sale/repository/SaleStockMovementRepository.java"));String dashboard=Files.readString(Path.of("src/main/java/com/fuelflex/platform/reception/repository/ReceptionStockBalanceRepository.java"));assertThat(repository).contains("m.sale.shiftAssignment.status='OPEN'");assertThat(dashboard).contains("shift.status='OPEN'","metered_stock_movements");}
 @Test void consolidationCreatesExactSourceMovementOnce(){MeteredStockMovementRepository repo=mock(MeteredStockMovementRepository.class);AssignmentFuelSourceResolver resolver=mock(AssignmentFuelSourceResolver.class);PumpShiftAssignment shift=shift("1000","1100");Tank source=new Tank();source.setId(UUID.randomUUID());Product product=new Product();product.setId(UUID.randomUUID());when(resolver.resolve(shift)).thenReturn(new AssignmentFuelSourceResolver.Source(null,source,product));when(repo.saveAndFlush(any())).thenAnswer(i->i.getArgument(0));User actor=new User();MeteredStockMovementService service=new MeteredStockMovementService(repo,resolver);MeteredStockMovement movement=service.consolidate(shift,actor);assertThat(movement.getTank()).isSameAs(source);assertThat(movement.getQuantity()).isEqualByComparingTo("100.000");assertThat(movement.getMovementType()).isEqualTo("METERED_OUTBOUND");verify(repo).saveAndFlush(any());}
 @Test void consolidationIsIdempotent(){MeteredStockMovementRepository repo=mock(MeteredStockMovementRepository.class);PumpShiftAssignment shift=shift("1000","1100");when(repo.existsByShiftAssignmentId(shift.getId())).thenReturn(true);MeteredStockMovementService service=new MeteredStockMovementService(repo,mock(AssignmentFuelSourceResolver.class));assertThatThrownBy(()->service.consolidate(shift,new User())).isInstanceOf(ConflictException.class);verify(repo,never()).saveAndFlush(any());}
 private PumpShiftAssignment shift(String opening,String closing){OperationalDay day=new OperationalDay();day.setStation(new Station());PumpShiftAssignment s=new PumpShiftAssignment();s.setId(UUID.randomUUID());s.setOperationalDay(day);s.setOpeningIndex(new BigDecimal(opening));s.setClosingIndex(new BigDecimal(closing));return s;}private BigDecimal finalStock(String metered,String returned){return BigDecimal.ZERO.subtract(new BigDecimal(metered)).add(new BigDecimal(returned));}private BigDecimal stock(String initial,String metered,String returned){return new BigDecimal(initial).subtract(new BigDecimal(metered)).add(new BigDecimal(returned));}private BigDecimal reconciliation(String metered,String cash,String credit,String returned){return new BigDecimal(metered).subtract(new BigDecimal(cash)).subtract(new BigDecimal(credit)).subtract(new BigDecimal(returned));}
}
