package com.fuelflex.platform.operations.blocktwo;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import java.math.*;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;
import com.fuelflex.platform.common.exception.ConflictException;import com.fuelflex.platform.operations.entity.*;import com.fuelflex.platform.operations.repository.*;import com.fuelflex.platform.operations.service.*;import com.fuelflex.platform.reception.repository.ReceptionStockBalanceRepository;import com.fuelflex.platform.sale.repository.SaleStockMovementRepository;import com.fuelflex.platform.station.entity.Station;import com.fuelflex.platform.tank.entity.Tank;import com.fuelflex.platform.tank.repository.TankRepository;import com.fuelflex.platform.user.entity.User;
@ExtendWith(MockitoExtension.class) class OperationalDayClosingServiceTest {
 @Mock PumpShiftAssignmentRepository shifts;@Mock ShiftReconciliationRepository recs;@Mock TankGaugeReadingRepository gauges;@Mock TankRepository tanks;@Mock DailyExpenseRepository expenses;@Mock ReceptionStockBalanceRepository inbound;@Mock SaleStockMovementRepository outbound;@Mock MeteredStockMovementRepository metered;@Mock TankReturnSourceMovementRepository returnSources;@Mock TankReturnStockMovementRepository returnMovements;@Mock OperationalDaySummaryRepository summaries;@Mock SupervisorOperationalNotifier notifier;OperationalDayClosingService service;OperationalDay day;User actor;
 @BeforeEach void setup(){service=new OperationalDayClosingService(shifts,recs,gauges,tanks,expenses,inbound,outbound,metered,returnSources,returnMovements,summaries,notifier);Station station=new Station();station.setId(UUID.randomUUID());day=new OperationalDay();day.setId(UUID.randomUUID());day.setStation(station);actor=new User();actor.setId(UUID.randomUUID());}
 @Test void openShiftBlocksClose(){when(shifts.countByOperationalDayIdAndStatus(day.getId(),OperationalStatus.OPEN)).thenReturn(1L);assertThatThrownBy(()->service.prepare(day,actor)).isInstanceOf(ConflictException.class).hasMessageContaining("1");}
 @Test void closeRefreshesGaugeAndSnapshotsDefinitiveReconciliations(){Tank t=new Tank();t.setId(UUID.randomUUID());TankGaugeReading g=new TankGaugeReading();g.setTank(t);g.setPhysicalStock(new BigDecimal("945.000"));ShiftReconciliation r=new ShiftReconciliation();r.setCashVolume(new BigDecimal("40"));r.setCreditVolume(new BigDecimal("20"));r.setTankReturnVolume(new BigDecimal("5"));r.setMeteredVolume(new BigDecimal("65"));r.setCashAmount(new BigDecimal("100"));r.setCreditAmount(new BigDecimal("50"));when(tanks.findByDepotStationIdAndActiveTrueOrderByDisplayOrderAscNameAsc(day.getStation().getId())).thenReturn(List.of(t));when(gauges.findByOperationalDayIdOrderByTankNameAsc(day.getId())).thenReturn(List.of(g));when(inbound.sumInboundByTankId(t.getId())).thenReturn(new BigDecimal("1000"));when(outbound.sumOutboundByTankId(t.getId())).thenReturn(new BigDecimal("60"));when(returnMovements.sumInboundByTankId(t.getId())).thenReturn(new BigDecimal("5"));when(shifts.countByOperationalDayId(day.getId())).thenReturn(1L);when(recs.countByShiftAssignmentOperationalDayId(day.getId())).thenReturn(1L);when(recs.findByShiftAssignmentOperationalDayIdOrderByShiftAssignmentOpenedAtAsc(day.getId())).thenReturn(List.of(r));when(expenses.sumByDayId(day.getId())).thenReturn(new BigDecimal("10"));when(summaries.save(any())).thenAnswer(i->i.getArgument(0));OperationalDaySummary s=service.prepare(day,actor);assertThat(g.getTheoreticalStock()).isEqualByComparingTo("945.000");assertThat(s.getTankReturnVolume()).isEqualByComparingTo("5.000");assertThat(s.getAccountedVolume()).isEqualByComparingTo("65.000");assertThat(s.getExpectedCash()).isEqualByComparingTo("100.000");assertThat(s.getExpectedNetCash()).isEqualByComparingTo("90.000");assertThat(s.getCreditAmount()).isEqualByComparingTo("50.000");}
}
