package com.fuelflex.platform.operations.blocktwo;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import java.math.*;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;
import com.fuelflex.platform.common.exception.ConflictException;import com.fuelflex.platform.operations.entity.*;import com.fuelflex.platform.operations.repository.*;import com.fuelflex.platform.operations.service.*;import com.fuelflex.platform.sale.entity.SaleType;import com.fuelflex.platform.sale.repository.FuelSaleRepository;import com.fuelflex.platform.station.entity.Station;import com.fuelflex.platform.tank.entity.Tank;import com.fuelflex.platform.tank.repository.TankRepository;import com.fuelflex.platform.user.entity.User;
@ExtendWith(MockitoExtension.class)class OperationalDayClosingServiceTest{
 @Mock PumpShiftAssignmentRepository shifts;@Mock ShiftReconciliationRepository recs;@Mock TankGaugeReadingRepository gauges;@Mock TankRepository tanks;@Mock FuelSaleRepository sales;@Mock DailyExpenseRepository expenses;@Mock OperationalDaySummaryRepository summaries;@Mock SupervisorOperationalNotifier notifier;OperationalDayClosingService service;OperationalDay day;User actor;
 @BeforeEach void setup(){service=new OperationalDayClosingService(shifts,recs,gauges,tanks,sales,expenses,summaries,notifier);Station station=new Station();station.setId(UUID.randomUUID());day=new OperationalDay();day.setId(UUID.randomUUID());day.setStation(station);actor=new User();actor.setId(UUID.randomUUID());}
 @Test void openShiftBlocksClose(){when(shifts.countByOperationalDayIdAndStatus(day.getId(),OperationalStatus.OPEN)).thenReturn(1L);assertThatThrownBy(()->service.prepare(day,actor)).isInstanceOf(ConflictException.class).hasMessageContaining("1");}
 @Test void missingGaugeBlocksClose(){when(shifts.countByOperationalDayId(day.getId())).thenReturn(0L);Tank t=new Tank();t.setId(UUID.randomUUID());t.setName("T1");when(tanks.findByDepotStationIdAndActiveTrueOrderByDisplayOrderAscNameAsc(day.getStation().getId())).thenReturn(List.of(t));assertThatThrownBy(()->service.prepare(day,actor)).isInstanceOf(ConflictException.class).hasMessageContaining("T1");}
 @Test void completeDataCreatesStableSummary(){when(shifts.countByOperationalDayId(day.getId())).thenReturn(0L);Tank t=new Tank();t.setId(UUID.randomUUID());TankGaugeReading g=new TankGaugeReading();g.setTank(t);g.setTheoreticalStock(new BigDecimal("900.000"));g.setPhysicalStock(new BigDecimal("895.000"));when(tanks.findByDepotStationIdAndActiveTrueOrderByDisplayOrderAscNameAsc(day.getStation().getId())).thenReturn(List.of(t));when(gauges.findByOperationalDayIdOrderByTankNameAsc(day.getId())).thenReturn(List.of(g));when(sales.sumEffectiveQuantityByDayAndType(day.getId(),SaleType.CASH)).thenReturn(new BigDecimal("100"));when(sales.sumEffectiveQuantityByDayAndType(day.getId(),SaleType.CREDIT)).thenReturn(new BigDecimal("50"));when(sales.sumEffectiveAmountByDayAndType(day.getId(),SaleType.CASH)).thenReturn(new BigDecimal("250"));when(sales.sumEffectiveAmountByDayAndType(day.getId(),SaleType.CREDIT)).thenReturn(new BigDecimal("125"));when(expenses.sumByDayId(day.getId())).thenReturn(new BigDecimal("10"));when(summaries.save(any())).thenAnswer(i->i.getArgument(0));OperationalDaySummary s=service.prepare(day,actor);assertThat(s.getSoldVolume()).isEqualByComparingTo("150.000");assertThat(s.getStockVariance()).isEqualByComparingTo("-5.000");verify(notifier).inform(actor,day.getStation(),"OPERATIONAL_DAY_CLOSED","OPERATIONAL_DAY",day.getId());}
}
