package com.fuelflex.platform.operations.blocktwo;

import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
import java.math.BigDecimal;import java.util.*;import org.junit.jupiter.api.*;
import com.fuelflex.platform.common.exception.BusinessException;import com.fuelflex.platform.operations.entity.*;import com.fuelflex.platform.operations.repository.*;import com.fuelflex.platform.operations.service.ShiftReconciliationService;import com.fuelflex.platform.product.entity.Product;import com.fuelflex.platform.sale.service.*;import com.fuelflex.platform.tank.entity.Tank;

class ShiftReconciliationServiceTest {
 private ShiftReconciliationRepository repo;private TankReturnRepository returns;private InternalConsumptionRepository internals;private PosConfigurationResolver pricing;private ShiftReconciliationService service;private PumpShiftAssignment shift;private Tank tank;private Product product;
 @BeforeEach void setup(){repo=mock(ShiftReconciliationRepository.class);returns=mock(TankReturnRepository.class);internals=mock(InternalConsumptionRepository.class);pricing=mock(PosConfigurationResolver.class);service=new ShiftReconciliationService(repo,returns,internals,pricing);shift=new PumpShiftAssignment();shift.setId(UUID.randomUUID());shift.setOpeningIndex(new BigDecimal("0.000"));shift.setClosingIndex(new BigDecimal("1000.000"));tank=new Tank();tank.setId(UUID.randomUUID());product=new Product();product.setId(UUID.randomUUID());ResolvedPosContext cash=new ResolvedPosContext(shift,null,null,tank,product,null,null,new BigDecimal("2.000"));ResolvedPosContext credit=new ResolvedPosContext(shift,null,null,tank,product,null,null,new BigDecimal("3.000"));when(pricing.resolve(shift)).thenReturn(cash);when(pricing.resolveCredit(shift)).thenReturn(credit);when(pricing.resolveInternal(shift)).thenReturn(cash);when(internals.sumQuantityByShiftId(shift.getId())).thenReturn(BigDecimal.ZERO);when(repo.findByShiftAssignmentId(shift.getId())).thenReturn(Optional.empty());when(repo.save(any())).thenAnswer(i->i.getArgument(0));}
 @Test void internalConsumptionIsExcludedFromSalesAndIncludedInAccountedVolume(){when(returns.sumQuantityByShiftId(shift.getId())).thenReturn(new BigDecimal("50"));when(internals.sumQuantityByShiftId(shift.getId())).thenReturn(new BigDecimal("100"));ShiftReconciliation r=service.calculate(shift,new BigDecimal("200"));assertThat(r.getCashVolume()).isEqualByComparingTo("650.000");assertThat(r.getInternalConsumptionVolume()).isEqualByComparingTo("100.000");assertThat(r.getInternalConsumptionAmount()).isEqualByComparingTo("200.000");assertThat(r.getAccountedVolume()).isEqualByComparingTo("1000.000");assertThat(r.getTurnover()).isEqualByComparingTo("1900.000");}
 @Test void scenario1NoReturnDerivesCash800AndCredit200(){when(returns.sumQuantityByShiftId(shift.getId())).thenReturn(BigDecimal.ZERO);ShiftReconciliation r=service.calculate(shift,new BigDecimal("200"));assertCommercial(r,"1000","0","800","200","1000","1600","600","2200");}
 @Test void scenario2SameTankReturnDerivesCash750AndSold950(){when(returns.sumQuantityByShiftId(shift.getId())).thenReturn(new BigDecimal("50"));ShiftReconciliation r=service.calculate(shift,new BigDecimal("200"));assertCommercial(r,"1000","50","750","200","950","1500","600","2100");}
 @Test void scenario3OtherDestinationDoesNotChangeCommercialSplit(){when(returns.sumQuantityByShiftId(shift.getId())).thenReturn(new BigDecimal("50"));ShiftReconciliation r=service.calculate(shift,new BigDecimal("200"));assertThat(r.getCashVolume()).isEqualByComparingTo("750.000");assertThat(r.getCreditVolume()).isEqualByComparingTo("200.000");assertThat(r.getTankReturnVolume()).isEqualByComparingTo("50.000");assertThat(r.getTurnover()).isEqualByComparingTo("2100.000");}
 @Test void scenario4CreditMayConsumeAllSaleableVolume(){when(returns.sumQuantityByShiftId(shift.getId())).thenReturn(new BigDecimal("20"));ShiftReconciliation r=service.calculate(shift,new BigDecimal("980"));assertThat(r.getCashVolume()).isEqualByComparingTo("0.000");assertThat(r.getCreditVolume()).isEqualByComparingTo("980.000");assertThat(r.getVolumeVariance()).isZero();}
 @Test void scenario5CreditAboveSaleableVolumeIsRejected(){when(returns.sumQuantityByShiftId(shift.getId())).thenReturn(new BigDecimal("50"));assertThatThrownBy(()->service.calculate(shift,new BigDecimal("951"))).isInstanceOf(BusinessException.class).hasMessageContaining("950.000");verify(repo,never()).save(any());}
 @Test void returnAboveMeteredVolumeIsRejected(){when(returns.sumQuantityByShiftId(shift.getId())).thenReturn(new BigDecimal("1000.001"));assertThatThrownBy(()->service.calculate(shift,BigDecimal.ZERO)).isInstanceOf(BusinessException.class).hasMessageContaining("dépasse");}
 @Test void definitiveReconciliationAlwaysHasZeroVariance(){when(returns.sumQuantityByShiftId(shift.getId())).thenReturn(new BigDecimal("50"));ShiftReconciliation r=service.calculate(shift,new BigDecimal("200"));assertThat(r.getMeteredVolume()).isEqualByComparingTo(r.getCashVolume().add(r.getCreditVolume()).add(r.getTankReturnVolume()));assertThat(r.getAccountedVolume()).isEqualByComparingTo(r.getMeteredVolume());assertThat(r.getVolumeVariance()).isZero();}
 private void assertCommercial(ShiftReconciliation r,String out,String returned,String cash,String credit,String sold,String cashAmount,String creditAmount,String turnover){assertThat(r.getMeteredVolume()).isEqualByComparingTo(out);assertThat(r.getTankReturnVolume()).isEqualByComparingTo(returned);assertThat(r.getCashVolume()).isEqualByComparingTo(cash);assertThat(r.getCreditVolume()).isEqualByComparingTo(credit);assertThat(r.getTotalSoldVolume()).isEqualByComparingTo(sold);assertThat(r.getCashAmount()).isEqualByComparingTo(cashAmount);assertThat(r.getCreditAmount()).isEqualByComparingTo(creditAmount);assertThat(r.getTurnover()).isEqualByComparingTo(turnover);assertThat(r.getSourceTank()).isSameAs(tank);assertThat(r.getProduct()).isSameAs(product);}
}
