package com.fuelflex.platform.operations.blocktwo;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import java.math.*;import java.time.OffsetDateTime;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;
import com.fuelflex.platform.common.exception.*;import com.fuelflex.platform.common.security.AuthorizationService;import com.fuelflex.platform.depot.entity.Depot;import com.fuelflex.platform.fuelmeter.entity.FuelMeter;import com.fuelflex.platform.operations.dto.TankReturnDtos.CreateRequest;import com.fuelflex.platform.operations.entity.*;import com.fuelflex.platform.operations.repository.*;import com.fuelflex.platform.operations.service.*;import com.fuelflex.platform.organization.entity.Organization;import com.fuelflex.platform.product.entity.Product;import com.fuelflex.platform.pump.entity.Pump;import com.fuelflex.platform.role.entity.Role;import com.fuelflex.platform.station.entity.Station;import com.fuelflex.platform.station.service.StationAccessService;import com.fuelflex.platform.tank.entity.*;import com.fuelflex.platform.tank.repository.TankRepository;import com.fuelflex.platform.user.entity.User;
@ExtendWith(MockitoExtension.class)class TankReturnServiceTest{
 @Mock AuthorizationService auth;@Mock PumpShiftAssignmentRepository shifts;@Mock OperationalDayRepository days;@Mock TankRepository tanks;@Mock TankReturnRepository returns;@Mock TankReturnStockMovementRepository destinations;@Mock TankReturnSourceMovementRepository sourcesLedger;@Mock AssignmentFuelSourceResolver sources;@Mock StationAccessService access;
 TankReturnService service;User manager;OperationalDay day;PumpShiftAssignment shift;Tank source,destination;Product product;
 @BeforeEach void setup(){service=new TankReturnService(auth,shifts,days,tanks,returns,destinations,sourcesLedger,sources,access);Organization org=new Organization();org.setId(UUID.randomUUID());Station station=new Station();station.setId(UUID.randomUUID());station.setOrganization(org);manager=user(org);day=new OperationalDay();day.setId(UUID.randomUUID());day.setOrganization(org);day.setStation(station);day.setStatus(OperationalStatus.OPEN);product=new Product();product.setId(UUID.randomUUID());Pump pump=new Pump();pump.setId(UUID.randomUUID());pump.setStation(station);FuelMeter meter=new FuelMeter();meter.setId(UUID.randomUUID());meter.setPump(pump);shift=new PumpShiftAssignment();shift.setId(UUID.randomUUID());shift.setOperationalDay(day);shift.setPumpAttendant(manager);shift.setFuelMeter(meter);shift.setStatus(OperationalStatus.OPEN);shift.setOpenedAt(OffsetDateTime.now().minusHours(1));Depot depot=new Depot();depot.setStation(station);source=tank(depot,product);destination=tank(depot,product);when(auth.getAuthenticatedUser()).thenReturn(manager);lenient().when(shifts.lockByIdAndOrganizationId(shift.getId(),org.getId())).thenReturn(Optional.of(shift));lenient().when(tanks.findByIdAndDepotStationId(destination.getId(),station.getId())).thenReturn(Optional.of(destination));lenient().when(sources.resolve(shift)).thenReturn(new AssignmentFuelSourceResolver.Source(pump,source,product));lenient().when(returns.saveAndFlush(any())).thenAnswer(i->{TankReturn r=i.getArgument(0);r.setId(UUID.randomUUID());r.setCreatedAt(OffsetDateTime.now());return r;});}
 @Test void createsDestinationCreditAndSourceDebit(){service.create(shift.getId(),request(destination,"20"));ArgumentCaptor<TankReturnStockMovement> in=ArgumentCaptor.forClass(TankReturnStockMovement.class);ArgumentCaptor<TankReturnSourceMovement> out=ArgumentCaptor.forClass(TankReturnSourceMovement.class);verify(destinations).saveAndFlush(in.capture());verify(sourcesLedger).saveAndFlush(out.capture());assertThat(in.getValue().getTank()).isSameAs(destination);assertThat(out.getValue().getTank()).isSameAs(source);assertThat(out.getValue().getQuantity()).isEqualByComparingTo("20.000");}
 @Test void rejectsClosedAssignmentOrDay(){shift.setStatus(OperationalStatus.CLOSED);assertThatThrownBy(()->service.create(shift.getId(),request(destination,"1"))).isInstanceOf(ConflictException.class);shift.setStatus(OperationalStatus.OPEN);day.setStatus(OperationalStatus.CLOSED);assertThatThrownBy(()->service.create(shift.getId(),request(destination,"1"))).isInstanceOf(ConflictException.class);}
 @Test void rejectsNonPositiveQuantity(){assertThatThrownBy(()->service.create(shift.getId(),request(destination,"0"))).isInstanceOf(BusinessException.class);}
 @Test void rejectsForeignStation(){when(tanks.findByIdAndDepotStationId(destination.getId(),day.getStation().getId())).thenReturn(Optional.empty());assertThatThrownBy(()->service.create(shift.getId(),request(destination,"1"))).isInstanceOf(ResourceNotFoundException.class);}
 @Test void rejectsIncompatibleProduct(){Product other=new Product();other.setId(UUID.randomUUID());Tank t=tank(destination.getDepot(),other);when(tanks.findByIdAndDepotStationId(t.getId(),day.getStation().getId())).thenReturn(Optional.of(t));assertThatThrownBy(()->service.create(shift.getId(),request(t,"1"))).isInstanceOf(BusinessException.class);}
 private Tank tank(Depot d,Product p){Tank t=new Tank();t.setId(UUID.randomUUID());t.setName("T");t.setDepot(d);t.setProduct(p);t.setActive(true);t.setStatus(TankStatus.ACTIVE);return t;}private CreateRequest request(Tank t,String q){return new CreateRequest(t.getId(),new BigDecimal(q),"Retour",OffsetDateTime.now().minusMinutes(1));}private User user(Organization o){Role r=new Role();r.setCode("MANAGER");r.setActive(true);User u=new User();u.setId(UUID.randomUUID());u.setFirstName("M");u.setLastName("N");u.setOrganization(o);u.setEnabled(true);u.setRoles(Set.of(r));return u;}
}
