package com.fuelflex.platform.purchaseorder.service.impl;

import java.time.OffsetDateTime;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.springframework.data.domain.*;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.transaction.annotation.Transactional;
import com.fuelflex.platform.common.exception.*;
import com.fuelflex.platform.common.security.AuthorizationService;
import com.fuelflex.platform.notification.service.NotificationService;
import com.fuelflex.platform.notification.dto.request.CreateNotificationCommand;
import com.fuelflex.platform.notification.entity.NotificationCategory;
import com.fuelflex.platform.notification.repository.NotificationRepository;
import com.fuelflex.platform.product.entity.Product;
import com.fuelflex.platform.product.repository.ProductRepository;
import com.fuelflex.platform.purchaseorder.dto.PurchaseOrderDtos.*;
import com.fuelflex.platform.purchaseorder.entity.*;
import com.fuelflex.platform.purchaseorder.model.*;
import com.fuelflex.platform.purchaseorder.repository.*;
import com.fuelflex.platform.purchaseorder.service.PurchaseOrderService;
import com.fuelflex.platform.purchaseorder.service.PurchaseOrderAttachmentStorageService;
import com.fuelflex.platform.station.entity.Station;
import com.fuelflex.platform.station.repository.StationRepository;
import com.fuelflex.platform.station.service.StationAccessService;
import com.fuelflex.platform.stationproduct.repository.StationProductRepository;
import com.fuelflex.platform.supplier.entity.OrganizationSupplier;
import com.fuelflex.platform.supplier.repository.*;
import com.fuelflex.platform.user.entity.User;
import com.fuelflex.platform.user.repository.UserRepository;
import jakarta.persistence.EntityManager;
import lombok.RequiredArgsConstructor;

@Service @RequiredArgsConstructor @Transactional
public class PurchaseOrderServiceImpl implements PurchaseOrderService {
 private final PurchaseOrderRepository orders; private final PurchaseOrderHistoryRepository history; private final PurchaseOrderNumberRepository numbers;
 private final StationRepository stations; private final ProductRepository products; private final StationProductRepository stationProducts;
 private final OrganizationSupplierRepository partnerships; private final SupplierUserMembershipRepository memberships;
 private final StationAccessService stationAccess; private final AuthorizationService authorization; private final EntityManager entityManager; private final NotificationService notifications; private final NotificationRepository notificationRepository; private final UserRepository users; private final PurchaseOrderAttachmentRepository attachments; private final PurchaseOrderAttachmentStorageService attachmentStorage;

 public Response create(CreateRequest r){User a=current();role(a,"MANAGER");PurchaseOrder po=new PurchaseOrder();po.setOrganization(org(a));apply(po,r.stationId(),r.organizationSupplierId(),r.items(),a);po.setOrderNumber("FF-PO-"+OffsetDateTime.now().getYear()+"-"+String.format("%06d",numbers.nextValue()));po.setCreatedBy(a);orders.save(po);event(po,null,PurchaseOrderStatus.DRAFT,PurchaseOrderAction.ORDER_CREATED,a,null);return response(po);}
 public Response update(UUID id,UpdateRequest r){User a=current();role(a,"MANAGER");PurchaseOrder po=manager(id,a,true);status(po,PurchaseOrderStatus.DRAFT);apply(po,r.stationId(),r.organizationSupplierId(),r.items(),a);event(po,po.getStatus(),po.getStatus(),PurchaseOrderAction.ORDER_UPDATED,a,null);return response(po);}
 public Response submit(UUID id){User a=current();role(a,"MANAGER");PurchaseOrder po=manager(id,a,true);status(po,PurchaseOrderStatus.DRAFT);if(po.getItems().isEmpty())throw new BusinessException("La commande doit contenir au moins un produit avant soumission.");po.setSubmittedAt(OffsetDateTime.now());move(po,PurchaseOrderStatus.PENDING_SUPERVISOR_APPROVAL,PurchaseOrderAction.ORDER_SUBMITTED,a,null);return response(po);}
 @Transactional(readOnly=true) public Page<Response> managerOrders(Pageable p){User a=current();role(a,"MANAGER");Set<UUID> ids=stationAccess.getAccessibleStationIds(a);return ids.isEmpty()?Page.empty(p):orders.findByOrganizationIdAndStationIdIn(org(a).getId(),ids,p).map(this::response);}
 @Transactional(readOnly=true) public Response managerOrder(UUID id){User a=current();role(a,"MANAGER");return response(manager(id,a,false));}
 @Transactional(readOnly=true) public List<HistoryResponse> managerHistory(UUID id){User a=current();role(a,"MANAGER");return histories(manager(id,a,false));}
 @Transactional(readOnly=true) public Page<Response> supervisorOrders(Pageable p){User a=current();role(a,"SUPERVISOR");return orders.findByOrganizationId(org(a).getId(),p).map(this::response);}
 @Transactional(readOnly=true) public Page<Response> supervisorPendingOrders(Pageable p){User a=current();role(a,"SUPERVISOR");return orders.findByOrganizationIdAndStatus(org(a).getId(),PurchaseOrderStatus.PENDING_SUPERVISOR_APPROVAL,p).map(this::response);}
 @Transactional(readOnly=true) public long supervisorPendingCount(){User a=current();role(a,"SUPERVISOR");return orders.countByOrganizationIdAndStatus(org(a).getId(),PurchaseOrderStatus.PENDING_SUPERVISOR_APPROVAL);}
 @Transactional(readOnly=true) public Response supervisorOrder(UUID id){User a=current();role(a,"SUPERVISOR");return response(tenant(id,a,false));}
 @Transactional(readOnly=true) public List<HistoryResponse> supervisorHistory(UUID id){User a=current();role(a,"SUPERVISOR");return histories(tenant(id,a,false));}
 public Response supervisorApprove(UUID id,DecisionRequest r){User a=current();role(a,"SUPERVISOR");PurchaseOrder po=tenant(id,a,true);status(po,PurchaseOrderStatus.PENDING_SUPERVISOR_APPROVAL);boolean integrated=po.getOrganizationSupplier()!=null&&selectable(po.getOrganizationSupplier())&&memberships.hasActivePortalUser(po.getOrganizationSupplier().getSupplier().getId());move(po,integrated?PurchaseOrderStatus.PENDING_SUPPLIER_APPROVAL:PurchaseOrderStatus.AWAITING_RECEPTION,PurchaseOrderAction.SUPERVISOR_APPROVED,a,comment(r));po.setSupervisorReviewedBy(a);po.setSupervisorReviewedAt(OffsetDateTime.now());return response(po);}
 public Response supervisorReject(UUID id,DecisionRequest r){User a=current();role(a,"SUPERVISOR");PurchaseOrder po=tenant(id,a,true);status(po,PurchaseOrderStatus.PENDING_SUPERVISOR_APPROVAL);move(po,PurchaseOrderStatus.SUPERVISOR_REJECTED,PurchaseOrderAction.SUPERVISOR_REJECTED,a,reason(r));po.setSupervisorReviewedBy(a);po.setSupervisorReviewedAt(OffsetDateTime.now());return response(po);}
 @Transactional(readOnly=true) public Page<Response> supplierOrders(Pageable p){User a=current();Set<UUID> ids=supplierIds(a);if(ids.isEmpty())return Page.empty(p);return entityManager.createQuery("select po from PurchaseOrder po join po.organizationSupplier os where os.supplier.id in :ids order by po.createdAt desc",PurchaseOrder.class).setParameter("ids",ids).setFirstResult((int)p.getOffset()).setMaxResults(p.getPageSize()).getResultStream().map(this::response).collect(Collectors.collectingAndThen(Collectors.toList(),x->new PageImpl<>(x,p,countSupplier(ids))));}
 @Transactional(readOnly=true) public Response supplierOrder(UUID id){User a=current();return response(supplier(id,supplierIds(a),false));}
 @Transactional(readOnly=true) public List<HistoryResponse> supplierHistory(UUID id){User a=current();return histories(supplier(id,supplierIds(a),false));}
 public Response supplierApprove(UUID id,DecisionRequest r){User a=current();PurchaseOrder po=supplier(id,supplierIds(a),true);status(po,PurchaseOrderStatus.PENDING_SUPPLIER_APPROVAL);requireActiveSupplier(po);move(po,PurchaseOrderStatus.AWAITING_RECEPTION,PurchaseOrderAction.SUPPLIER_APPROVED,a,comment(r));po.setSupplierReviewedBy(a);po.setSupplierReviewedAt(OffsetDateTime.now());return response(po);}
 public Response supplierReject(UUID id,DecisionRequest r){User a=current();PurchaseOrder po=supplier(id,supplierIds(a),true);status(po,PurchaseOrderStatus.PENDING_SUPPLIER_APPROVAL);requireActiveSupplier(po);move(po,PurchaseOrderStatus.SUPPLIER_REJECTED,PurchaseOrderAction.SUPPLIER_REJECTED,a,reason(r));po.setSupplierReviewedBy(a);po.setSupplierReviewedAt(OffsetDateTime.now());return response(po);}

 private void apply(PurchaseOrder po,UUID stationId,UUID partnershipId,List<ItemRequest> requests,User a){Station station=stations.findByIdAndOrganizationId(stationId,org(a).getId()).orElseThrow(this::missing);stationAccess.checkStationAccess(a,stationId);po.setStation(station);po.setOrganizationSupplier(partnership(partnershipId,org(a).getId()));List<ItemRequest> safe=requests==null?List.of():requests;Set<UUID> ids=new HashSet<>();for(ItemRequest x:safe)if(!ids.add(x.productId()))throw new BusinessException("Produit dupliqué dans le panier.");Map<UUID,Product> found=products.findAllById(ids).stream().collect(Collectors.toMap(Product::getId,Function.identity()));List<PurchaseOrderItem> items=new ArrayList<>();for(ItemRequest x:safe){Product product=found.get(x.productId());if(product==null||!product.isActive()||!product.getOrganization().getId().equals(po.getOrganization().getId())||stationProducts.findByStationIdAndProductId(stationId,x.productId()).filter(sp->sp.isActive()).isEmpty())throw new ResourceNotFoundException("Produit indisponible pour cette station.");PurchaseOrderItem item=new PurchaseOrderItem();item.setProduct(product);item.setQuantity(x.quantity());items.add(item);}po.replaceItems(items);}
 private OrganizationSupplier partnership(UUID id,UUID orgId){if(id==null)return null;OrganizationSupplier os=partnerships.findByIdAndOrganizationId(id,orgId).orElseThrow(this::missing);if(!selectable(os))throw new BusinessException("Partenariat fournisseur non sélectionnable.");return os;}
 private boolean selectable(OrganizationSupplier os){return os.isActive()&&os.getSupplier().isActive();}
 private void requireActiveSupplier(PurchaseOrder po){if(po.getOrganizationSupplier()==null||!po.getOrganizationSupplier().getSupplier().isActive())throw new ConflictException("Le fournisseur n’est plus actif.");}
 private PurchaseOrder manager(UUID id,User a,boolean lock){PurchaseOrder po=tenant(id,a,lock);if(!po.getCreatedBy().getId().equals(a.getId())||!stationAccess.canAccessStation(a,po.getStation().getId()))throw missing();return po;}
 private PurchaseOrder tenant(UUID id,User a,boolean lock){UUID oid=org(a).getId();return(lock?orders.lockByIdAndOrganizationId(id,oid):orders.findByIdAndOrganizationId(id,oid)).orElseThrow(this::missing);}
 private PurchaseOrder supplier(UUID id,Set<UUID> ids,boolean lock){for(UUID sid:ids){Optional<PurchaseOrder> result=lock?orders.lockByIdForSupplier(id,sid):orders.findByIdForSupplier(id,sid);if(result.isPresent())return result.get();}throw missing();}
 private Set<UUID> supplierIds(User a){role(a,"SUPPLIER_USER");return new HashSet<>(entityManager.createQuery("select distinct m.supplier.id from SupplierUserMembership m where m.user.id=:uid and m.active=true",UUID.class).setParameter("uid",a.getId()).getResultList());}
 private long countSupplier(Set<UUID> ids){return entityManager.createQuery("select count(po) from PurchaseOrder po join po.organizationSupplier os where os.supplier.id in :ids",Long.class).setParameter("ids",ids).getSingleResult();}
 private void move(PurchaseOrder po,PurchaseOrderStatus to,PurchaseOrderAction action,User a,String c){PurchaseOrderStatus from=po.getStatus();po.setStatus(to);event(po,from,to,action,a,c);}
 private void event(PurchaseOrder po,PurchaseOrderStatus from,PurchaseOrderStatus to,PurchaseOrderAction action,User a,String c){PurchaseOrderHistory h=new PurchaseOrderHistory();h.setPurchaseOrder(po);h.setFromStatus(from);h.setToStatus(to);h.setAction(action);h.setPerformedBy(a);h.setComment(c);history.save(h);notifyForEvent(po,action,a);}
 private void notifyForEvent(PurchaseOrder po,PurchaseOrderAction action,User actor){if(notifications==null)return;String event=action==PurchaseOrderAction.ORDER_SUBMITTED?"ORDER_SUBMITTED":action==PurchaseOrderAction.SUPERVISOR_APPROVED?"ORDER_SUPERVISOR_APPROVED":action==PurchaseOrderAction.SUPERVISOR_REJECTED?"ORDER_SUPERVISOR_REJECTED":action==PurchaseOrderAction.SUPPLIER_APPROVED?"ORDER_SUPPLIER_APPROVED":"ORDER_SUPPLIER_REJECTED";String title=action==PurchaseOrderAction.ORDER_SUBMITTED?"notifications:events.orderSubmitted.title":action==PurchaseOrderAction.SUPERVISOR_APPROVED?"notifications:events.orderApproved.title":action==PurchaseOrderAction.SUPERVISOR_REJECTED?"notifications:events.orderRejected.title":action==PurchaseOrderAction.SUPPLIER_APPROVED?"notifications:events.orderApproved.title":action==PurchaseOrderAction.SUPPLIER_REJECTED?"notifications:events.orderRejected.title":null;if(title==null)return;String message=action==PurchaseOrderAction.ORDER_SUBMITTED?"notifications:events.orderSubmitted.message":action==PurchaseOrderAction.SUPERVISOR_APPROVED?"notifications:events.orderApproved.message":action==PurchaseOrderAction.SUPERVISOR_REJECTED?"notifications:events.orderRejected.message":action==PurchaseOrderAction.SUPPLIER_APPROVED?"notifications:events.orderApproved.message":"notifications:events.orderRejected.message";List<User> recipients=action==PurchaseOrderAction.ORDER_SUBMITTED?users.findEnabledByOrganizationIdAndRoleCode(po.getOrganization().getId(),"SUPERVISOR"):Collections.singletonList(po.getCreatedBy());for(User recipient:recipients){if(recipient==null||notificationsAlreadyExist(recipient,event,po.getId()))continue;notifications.create(CreateNotificationCommand.builder().recipientId(recipient.getId()).organizationId(po.getOrganization().getId()).stationId(po.getStation().getId()).actorId(actor.getId()).eventType(event).category(action==PurchaseOrderAction.ORDER_SUBMITTED?NotificationCategory.ACTION_REQUIRED:NotificationCategory.INFORMATION).titleKey(title).messageKey(message).resourceType("PURCHASE_ORDER").resourceId(po.getId()).requiresAction(action==PurchaseOrderAction.ORDER_SUBMITTED).build());}}
 private boolean notificationsAlreadyExist(User recipient,String event,UUID resourceId){return notificationRepository != null && notificationRepository.existsByRecipientIdAndEventTypeAndResourceId(recipient.getId(),event,resourceId);}
 private List<HistoryResponse> histories(PurchaseOrder po){return history.findByPurchaseOrderIdOrderByPerformedAtAscIdAsc(po.getId()).stream().map(h->new HistoryResponse(h.getId(),h.getAction(),h.getFromStatus(),h.getToStatus(),user(h.getPerformedBy()),h.getPerformedAt(),h.getComment())).toList();}
 private void status(PurchaseOrder po,PurchaseOrderStatus expected){if(po.getStatus()!=expected)throw new ConflictException("Transition impossible depuis "+po.getStatus()+".");}
 private String reason(DecisionRequest r){String c=comment(r);if(c==null)throw new BusinessException("Un motif est obligatoire.");return c;} private String comment(DecisionRequest r){return r==null||r.comment()==null||r.comment().isBlank()?null:r.comment().trim();}
 private User current(){return authorization.getAuthenticatedUser();} private com.fuelflex.platform.organization.entity.Organization org(User a){if(a.getOrganization()==null)throw new ForbiddenException("Organisation requise.");return a.getOrganization();}
 private void role(User a,String code){if(a==null||!a.isEnabled()||a.getRoles().stream().noneMatch(r->r.isActive()&&r.getCode().equalsIgnoreCase(code)))throw new ForbiddenException("Rôle requis: "+code);}
 private ResourceNotFoundException missing(){return new ResourceNotFoundException("Commande introuvable.");}
 private Response response(PurchaseOrder po){OrganizationSupplier os=po.getOrganizationSupplier();SupplierSummary supplier=os==null?null:new SupplierSummary(os.getId(),os.getSupplier().getId(),os.getSupplier().getDisplayName(),memberships.hasActivePortalUser(os.getSupplier().getId()));return new Response(po.getId(),po.getOrderNumber(),organization(po.getOrganization()),new StationDocumentSummary(po.getStation().getId(),po.getStation().getCode(),po.getStation().getName(),po.getStation().getAddress(),po.getStation().getCity(),po.getStation().getProvince(),po.getStation().getCountry()),supplier,po.getStatus(),po.getItems().stream().map(i->new ItemResponse(i.getId(),i.getProduct().getId(),i.getProduct().getCode(),i.getProduct().getName(),i.getProduct().getUnit().name(),i.getQuantity())).toList(),user(po.getCreatedBy()),po.getCreatedAt(),po.getUpdatedAt(),po.getSubmittedAt(),user(po.getSupervisorReviewedBy()),po.getSupervisorReviewedAt(),user(po.getSupplierReviewedBy()),po.getSupplierReviewedAt(),po.getVersion(),attachments == null ? List.of() : attachments.findByPurchaseOrderIdOrderByUploadedAtAsc(po.getId()).stream().map(this::attachmentResponse).toList());}
 private UserSummary user(User u){return u==null?null:new UserSummary(u.getId(),u.getFirstName(),u.getLastName());}
 public AttachmentResponse uploadAttachment(UUID orderId,String displayName,MultipartFile file){User a=current();role(a,"MANAGER");PurchaseOrder po=manager(orderId,a,true);status(po,PurchaseOrderStatus.DRAFT);if(displayName==null||displayName.isBlank())throw new BusinessException("L’intitulé est obligatoire.");if(attachments.countByPurchaseOrderId(orderId)>=2)throw new BusinessException("Deux pièces jointes maximum.");PurchaseOrderAttachment x=new PurchaseOrderAttachment();x.setPurchaseOrder(po);x.setDisplayName(displayName.trim());x.setOriginalFilename(file.getOriginalFilename()==null?"document":file.getOriginalFilename());x.setContentType(file.getContentType());x.setFileSize(file.getSize());x.setUploadedBy(a);x.setStorageKey(attachmentStorage.store(org(a).getId(),orderId,file));return attachmentResponse(attachments.save(x));}
 public List<AttachmentResponse> attachments(UUID orderId){User a=current();boolean supervisor=a.getRoles().stream().anyMatch(r->r.getCode().equalsIgnoreCase("SUPERVISOR"));PurchaseOrder po=supervisor?tenant(orderId,a,false):manager(orderId,a,false);return attachments == null ? List.of() : attachments.findByPurchaseOrderIdOrderByUploadedAtAsc(po.getId()).stream().map(this::attachmentResponse).toList();}
 public AttachmentDownload downloadAttachment(UUID orderId,UUID attachmentId){User a=current();PurchaseOrder po=tenant(orderId,a,false);PurchaseOrderAttachment x=attachments.findByIdAndPurchaseOrderOrganizationId(attachmentId,org(a).getId()).filter(v->v.getPurchaseOrder().getId().equals(po.getId())).orElseThrow(this::missing);return new AttachmentDownload(attachmentStorage.read(x.getStorageKey()),x.getContentType(),x.getOriginalFilename());}
 public void deleteAttachment(UUID orderId,UUID attachmentId){User a=current();role(a,"MANAGER");PurchaseOrder po=manager(orderId,a,true);status(po,PurchaseOrderStatus.DRAFT);PurchaseOrderAttachment x=attachments.findByIdAndPurchaseOrderOrganizationId(attachmentId,org(a).getId()).filter(v->v.getPurchaseOrder().getId().equals(po.getId())).orElseThrow(this::missing);attachmentStorage.delete(x.getStorageKey());attachments.delete(x);}
 private OrganizationSummary organization(com.fuelflex.platform.organization.entity.Organization o){return new OrganizationSummary(o.getId(),o.getName(),o.getTradeName(),o.getRegistrationNumber(),o.getNationalId(),o.getTaxNumber(),o.getLogoUrl(),o.getAddress(),o.getCity(),o.getProvince(),o.getCountry());}
 private AttachmentResponse attachmentResponse(PurchaseOrderAttachment x){return new AttachmentResponse(x.getId(),x.getDisplayName(),x.getOriginalFilename(),x.getContentType(),x.getFileSize(),user(x.getUploadedBy()),x.getUploadedAt());}
}
