package com.fuelflex.platform.creditcustomer.service;
import static com.fuelflex.platform.creditcustomer.dto.CreditCustomerDtos.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.fuelflex.platform.common.exception.*; import com.fuelflex.platform.common.security.AuthorizationService; import com.fuelflex.platform.creditcustomer.entity.CreditCustomer; import com.fuelflex.platform.creditcustomer.repository.CreditCustomerRepository; import com.fuelflex.platform.role.entity.Role; import com.fuelflex.platform.user.entity.User; import lombok.RequiredArgsConstructor;
@Service @RequiredArgsConstructor @Transactional public class CreditCustomerServiceImpl implements CreditCustomerService{
 private final CreditCustomerRepository customers;private final AuthorizationService authorization;
 public Response create(Request r){User a=manager();UUID org=a.getOrganization().getId();if(customers.existsByOrganizationIdAndCodeIgnoreCase(org,r.code()))throw new ConflictException("Ce code client crédit existe déjà.");if(customers.existsByOrganizationIdAndNameIgnoreCase(org,r.name()))throw new ConflictException("Ce client crédit existe déjà.");CreditCustomer c=new CreditCustomer();c.setOrganization(a.getOrganization());apply(c,r);return response(customers.save(c));}
 public Response update(UUID id,Request r){User a=manager();CreditCustomer c=customers.findByIdAndOrganizationId(id,a.getOrganization().getId()).orElseThrow(()->new ResourceNotFoundException("Client crédit introuvable."));if(!c.getCode().equalsIgnoreCase(r.code())&&customers.existsByOrganizationIdAndCodeIgnoreCase(a.getOrganization().getId(),r.code()))throw new ConflictException("Ce code client crédit existe déjà.");apply(c,r);return response(customers.save(c));}
 @Transactional(readOnly=true)public List<Response> managerList(){User a=manager();return customers.findByOrganizationIdOrderByNameAsc(a.getOrganization().getId()).stream().map(this::response).toList();}
 @Transactional(readOnly=true)public List<Response> posSelectable(){User a=role("PUMP_ATTENDANT");return customers.findByOrganizationIdAndActiveTrueOrderByNameAsc(a.getOrganization().getId()).stream().map(this::response).toList();}
 private void apply(CreditCustomer c,Request r){c.setCode(r.code());c.setName(r.name());c.setPhone(r.phone());c.setEmail(r.email());c.setActive(r.active()==null||r.active());}
 private User manager(){return role("MANAGER");}private User role(String code){User a=authorization.getAuthenticatedUser();if(a==null||!a.isEnabled()||a.getOrganization()==null||a.getRoles().stream().filter(Role::isActive).noneMatch(r->code.equalsIgnoreCase(r.getCode())))throw new ForbiddenException("Rôle requis: "+code);return a;}
 private Response response(CreditCustomer c){return new Response(c.getId(),c.getCode(),c.getName(),c.getPhone(),c.getEmail(),c.isActive());}
}
