package com.fuelflex.platform.purchaseorder.service.impl;
import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
import java.util.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension;
import com.fuelflex.platform.common.exception.*; import com.fuelflex.platform.common.security.AuthorizationService; import com.fuelflex.platform.organization.entity.Organization;
import com.fuelflex.platform.product.repository.ProductRepository; import com.fuelflex.platform.purchaseorder.dto.PurchaseOrderDtos.DecisionRequest; import com.fuelflex.platform.purchaseorder.entity.*; import com.fuelflex.platform.purchaseorder.model.*; import com.fuelflex.platform.purchaseorder.repository.*;
import com.fuelflex.platform.role.entity.Role; import com.fuelflex.platform.station.entity.Station; import com.fuelflex.platform.station.repository.StationRepository; import com.fuelflex.platform.station.service.StationAccessService; import com.fuelflex.platform.stationproduct.repository.StationProductRepository;
import com.fuelflex.platform.supplier.entity.*; import com.fuelflex.platform.supplier.repository.*; import com.fuelflex.platform.user.entity.User; import jakarta.persistence.EntityManager;
@ExtendWith(MockitoExtension.class)
class PurchaseOrderWorkflowTest {
 @Mock PurchaseOrderRepository orders; @Mock PurchaseOrderHistoryRepository history; @Mock PurchaseOrderNumberRepository numbers; @Mock StationRepository stations; @Mock ProductRepository products; @Mock StationProductRepository stationProducts; @Mock OrganizationSupplierRepository partnerships; @Mock SupplierUserMembershipRepository memberships; @Mock StationAccessService stationAccess; @Mock AuthorizationService authorization; @Mock EntityManager entityManager; @Mock com.fuelflex.platform.notification.service.NotificationService notifications; @InjectMocks PurchaseOrderServiceImpl service;
 Organization org; User supervisor; PurchaseOrder po;
 @BeforeEach void setup(){org=new Organization();org.setId(UUID.randomUUID());supervisor=user("SUPERVISOR");when(authorization.getAuthenticatedUser()).thenReturn(supervisor);po=order(PurchaseOrderStatus.PENDING_SUPERVISOR_APPROVAL);when(orders.lockByIdAndOrganizationId(po.getId(),org.getId())).thenReturn(Optional.of(po));}
 @Test void approveWithoutSupplierAwaitsReception(){assertThat(service.supervisorApprove(po.getId(),null).status()).isEqualTo(PurchaseOrderStatus.AWAITING_RECEPTION);verify(history).save(argThat(h->h.getAction()==PurchaseOrderAction.SUPERVISOR_APPROVED));}
 @Test void approveNonIntegratedSupplierAwaitsReception(){po.setOrganizationSupplier(partnership(true,true));when(memberships.hasActivePortalUser(any())).thenReturn(false);assertThat(service.supervisorApprove(po.getId(),null).status()).isEqualTo(PurchaseOrderStatus.AWAITING_RECEPTION);}
 @Test void approveIntegratedSupplierWaitsForSupplier(){po.setOrganizationSupplier(partnership(true,true));when(memberships.hasActivePortalUser(any())).thenReturn(true);assertThat(service.supervisorApprove(po.getId(),null).status()).isEqualTo(PurchaseOrderStatus.PENDING_SUPPLIER_APPROVAL);}
 @Test void integratedIsRecalculatedAtDecisionTime(){po.setOrganizationSupplier(partnership(true,true));when(memberships.hasActivePortalUser(any())).thenReturn(false);service.supervisorApprove(po.getId(),null);verify(memberships,atLeastOnce()).hasActivePortalUser(po.getOrganizationSupplier().getSupplier().getId());}
 @Test void supervisorRejectRequiresReason(){assertThatThrownBy(()->service.supervisorReject(po.getId(),new DecisionRequest(" "))).isInstanceOf(BusinessException.class);}
 @Test void supervisorRejectStoresReason(){service.supervisorReject(po.getId(),new DecisionRequest("budget"));assertThat(po.getStatus()).isEqualTo(PurchaseOrderStatus.SUPERVISOR_REJECTED);verify(history).save(argThat(h->"budget".equals(h.getComment())));}
 @Test void wrongSupervisorStateIsRejected(){po.setStatus(PurchaseOrderStatus.DRAFT);assertThatThrownBy(()->service.supervisorApprove(po.getId(),null)).isInstanceOf(ConflictException.class);}
 @Test void crossTenantSupervisorGetsNotFound(){when(orders.lockByIdAndOrganizationId(po.getId(),org.getId())).thenReturn(Optional.empty());assertThatThrownBy(()->service.supervisorApprove(po.getId(),null)).isInstanceOf(ResourceNotFoundException.class);}
 private User user(String code){Role r=new Role();r.setCode(code);r.setActive(true);User u=new User();u.setId(UUID.randomUUID());u.setOrganization(org);u.setEnabled(true);u.setRoles(Set.of(r));u.setFirstName("Paul");u.setLastName("Test");return u;}
 private PurchaseOrder order(PurchaseOrderStatus status){PurchaseOrder x=new PurchaseOrder();x.setId(UUID.randomUUID());x.setOrganization(org);x.setStation(Station.builder().id(UUID.randomUUID()).code("STA").name("Station").build());x.setCreatedBy(supervisor);x.setOrderNumber("FF-PO-2026-000001");x.setStatus(status);return x;}
 private OrganizationSupplier partnership(boolean active,boolean supplierActive){Supplier s=new Supplier();s.setId(UUID.randomUUID());s.setDisplayName("COBIL");s.setActive(supplierActive);OrganizationSupplier os=new OrganizationSupplier();os.setId(UUID.randomUUID());os.setOrganization(org);os.setSupplier(s);os.setActive(active);return os;}
}
