package com.fuelflex.platform.operations.service;
import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
import java.math.BigDecimal; import java.time.*; import java.util.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension;
import com.fuelflex.platform.assignment.repository.UserStationAssignmentRepository; import com.fuelflex.platform.common.exception.*; import com.fuelflex.platform.common.security.AuthorizationService; import com.fuelflex.platform.fuelmeter.entity.*; import com.fuelflex.platform.fuelmeter.repository.FuelMeterRepository; import com.fuelflex.platform.fuelmeter.service.MeteringConsistencyService; import com.fuelflex.platform.operations.dto.OperationalDtos.*; import com.fuelflex.platform.operations.entity.*; import com.fuelflex.platform.operations.repository.*; import com.fuelflex.platform.organization.entity.Organization; import com.fuelflex.platform.pump.entity.*; import com.fuelflex.platform.role.entity.Role; import com.fuelflex.platform.station.entity.Station; import com.fuelflex.platform.station.repository.StationRepository; import com.fuelflex.platform.station.service.StationAccessService; import com.fuelflex.platform.user.entity.User; import com.fuelflex.platform.user.repository.UserRepository;
@ExtendWith(MockitoExtension.class) class OperationalDayServiceImplTest {
 @Mock OperationalDayRepository days; @Mock PumpShiftAssignmentRepository shifts; @Mock OperationalHistoryRepository history; @Mock AuthorizationService auth; @Mock StationAccessService access; @Mock StationRepository stations; @Mock UserRepository users; @Mock UserStationAssignmentRepository admin; @Mock FuelMeterRepository meters; @Mock MeteringConsistencyService consistency;
 @Mock ShiftReconciliationService shiftReconciliation; @Mock OperationalDayClosingService dayClosing; @Mock SupervisorOperationalNotifier notifier;
 OperationalDayServiceImpl service; Organization org; Station station; User manager; User attendant; OperationalDay day; FuelMeter meter;
 @BeforeEach void setup(){service=new OperationalDayServiceImpl(days,shifts,history,auth,access,stations,users,admin,meters,new AssignmentMeterValidator(consistency),shiftReconciliation,dayClosing,notifier);org=new Organization();org.setId(UUID.randomUUID());station=new Station();station.setId(UUID.randomUUID());station.setName("Station A");station.setOrganization(org);station.setActive(true);manager=user("MANAGER",true);attendant=user("PUMP_ATTENDANT",true);attendant.setOperationalCode("PMP-000001");day=new OperationalDay();day.setId(UUID.randomUUID());day.setOrganization(org);day.setStation(station);day.setBusinessDate(LocalDate.now());day.setStatus(OperationalStatus.OPEN);day.setOpenedBy(manager);day.setOpenedAt(OffsetDateTime.now());Pump pump=new Pump();pump.setId(UUID.randomUUID());pump.setName("Pump 1");pump.setStation(station);pump.setActive(true);pump.setStatus(PumpStatus.ACTIVE);pump.setMeteringLevel(MeteringLevel.PUMP);meter=new FuelMeter();meter.setId(UUID.randomUUID());meter.setName("Meter 1");meter.setPump(pump);meter.setActive(true);meter.setStatus(FuelMeterStatus.ACTIVE);meter.setCurrentIndex(new BigDecimal("125000.000"));when(auth.getAuthenticatedUser()).thenReturn(manager);}
 @Test void createsOperationalDay(){when(stations.findByIdAndOrganizationId(station.getId(),org.getId())).thenReturn(Optional.of(station));when(days.saveAndFlush(any())).thenAnswer(i->{OperationalDay d=i.getArgument(0);d.setId(UUID.randomUUID());return d;});DayResponse result=service.open(new OpenDayRequest(station.getId(),LocalDate.now()));assertThat(result.status()).isEqualTo(OperationalStatus.OPEN);verify(history).save(any());verify(notifier).inform(eq(manager),eq(station),eq("OPERATIONAL_DAY_OPENED"),eq("OPERATIONAL_DAY"),any());}
 @Test void rejectsDuplicateOperationalDay(){when(stations.findByIdAndOrganizationId(station.getId(),org.getId())).thenReturn(Optional.of(station));when(days.existsByStationIdAndBusinessDate(any(),any())).thenReturn(true);assertThatThrownBy(()->service.open(new OpenDayRequest(station.getId(),LocalDate.now()))).isInstanceOf(ConflictException.class);}
 @Test void snapshotsCurrentIndexWhenAssigning(){arrangeValidAssignment();service.assign(day.getId(),new OpenAssignmentRequest(attendant.getId(),meter.getId()));ArgumentCaptor<PumpShiftAssignment> c=ArgumentCaptor.forClass(PumpShiftAssignment.class);verify(shifts).saveAndFlush(c.capture());assertThat(c.getValue().getOpeningIndex()).isEqualByComparingTo("125000.000");verify(notifier).inform(eq(manager),eq(station),eq("SHIFT_ASSIGNMENT_OPENED"),eq("SHIFT_ASSIGNMENT"),any());}
 @Test void rejectsWrongRole(){attendant.setRoles(Set.of(role("ACCOUNTANT")));when(days.lockByIdAndOrganizationId(day.getId(),org.getId())).thenReturn(Optional.of(day));when(users.lockByIdAndOrganizationId(attendant.getId(),org.getId())).thenReturn(Optional.of(attendant));assertThatThrownBy(()->service.assign(day.getId(),new OpenAssignmentRequest(attendant.getId(),meter.getId()))).isInstanceOf(BusinessException.class).hasMessageContaining("PUMP_ATTENDANT");}
 @Test void rejectsAttendantOutsideStation(){when(days.lockByIdAndOrganizationId(day.getId(),org.getId())).thenReturn(Optional.of(day));when(users.lockByIdAndOrganizationId(attendant.getId(),org.getId())).thenReturn(Optional.of(attendant));assertThatThrownBy(()->service.assign(day.getId(),new OpenAssignmentRequest(attendant.getId(),meter.getId()))).isInstanceOf(ForbiddenException.class);}
 @Test void rejectsOccupiedMeter(){arrangeValidAssignment();when(shifts.existsByFuelMeterIdAndStatus(meter.getId(),OperationalStatus.OPEN)).thenReturn(true);assertThatThrownBy(()->service.assign(day.getId(),new OpenAssignmentRequest(attendant.getId(),meter.getId()))).isInstanceOf(ConflictException.class).hasMessageContaining("fuel meter");}
 @Test void rejectsAlreadyAssignedAttendant(){arrangeValidAssignment();when(shifts.existsByPumpAttendantIdAndStatus(attendant.getId(),OperationalStatus.OPEN)).thenReturn(true);assertThatThrownBy(()->service.assign(day.getId(),new OpenAssignmentRequest(attendant.getId(),meter.getId()))).isInstanceOf(ConflictException.class).hasMessageContaining("pump attendant");}
 @Test void rejectsClosingIndexBelowOpening(){PumpShiftAssignment shift=openShift();when(shifts.lockByIdAndOrganizationId(shift.getId(),org.getId())).thenReturn(Optional.of(shift));assertThatThrownBy(()->service.closeAssignment(shift.getId(),new CloseAssignmentRequest(new BigDecimal("124999.999")))).isInstanceOf(BusinessException.class);}
 @Test void closesAssignmentCalculatesVolumeAndAdvancesMeter(){PumpShiftAssignment shift=openShift();when(shifts.lockByIdAndOrganizationId(shift.getId(),org.getId())).thenReturn(Optional.of(shift));when(meters.lockById(meter.getId())).thenReturn(Optional.of(meter));AssignmentResponse result=service.closeAssignment(shift.getId(),new CloseAssignmentRequest(new BigDecimal("126250.000")));assertThat(result.meteredVolume()).isEqualByComparingTo("1250.000");assertThat(meter.getCurrentIndex()).isEqualByComparingTo("126250.000");verify(notifier).inform(eq(manager),eq(station),eq("SHIFT_ASSIGNMENT_CLOSED"),eq("SHIFT_ASSIGNMENT"),eq(shift.getId()));}
 @Test void refusesDayCloseWithOpenShifts(){when(days.lockByIdAndOrganizationId(day.getId(),org.getId())).thenReturn(Optional.of(day));doThrow(new ConflictException("2 affectations restent ouvertes")).when(dayClosing).prepare(day,manager);assertThatThrownBy(()->service.close(day.getId())).isInstanceOf(ConflictException.class).hasMessageContaining("2");}
 @Test void closedDayRefusesAssignment(){day.setStatus(OperationalStatus.CLOSED);when(days.lockByIdAndOrganizationId(day.getId(),org.getId())).thenReturn(Optional.of(day));assertThatThrownBy(()->service.assign(day.getId(),new OpenAssignmentRequest(attendant.getId(),meter.getId()))).isInstanceOf(ConflictException.class);}
 @Test void rejectsInactiveAttendant(){attendant.setEnabled(false);when(days.lockByIdAndOrganizationId(day.getId(),org.getId())).thenReturn(Optional.of(day));when(users.lockByIdAndOrganizationId(attendant.getId(),org.getId())).thenReturn(Optional.of(attendant));assertThatThrownBy(()->service.assign(day.getId(),new OpenAssignmentRequest(attendant.getId(),meter.getId()))).isInstanceOf(BusinessException.class).hasMessageContaining("inactive");}
 @Test void rejectsMeterOutsideStation(){arrangeValidAssignment();Station other=new Station();other.setId(UUID.randomUUID());meter.getPump().setStation(other);assertThatThrownBy(()->service.assign(day.getId(),new OpenAssignmentRequest(attendant.getId(),meter.getId()))).isInstanceOf(ForbiddenException.class);}
 @Test void rejectsDoubleAssignmentClose(){PumpShiftAssignment shift=openShift();shift.setStatus(OperationalStatus.CLOSED);shift.setClosingIndex(new BigDecimal("125001.000"));when(shifts.lockByIdAndOrganizationId(shift.getId(),org.getId())).thenReturn(Optional.of(shift));assertThatThrownBy(()->service.closeAssignment(shift.getId(),new CloseAssignmentRequest(new BigDecimal("125002.000")))).isInstanceOf(ConflictException.class);}
 @Test void nextAssignmentUsesPreviousClosingIndex(){PumpShiftAssignment shift=openShift();when(shifts.lockByIdAndOrganizationId(shift.getId(),org.getId())).thenReturn(Optional.of(shift));when(meters.lockById(meter.getId())).thenReturn(Optional.of(meter));service.closeAssignment(shift.getId(),new CloseAssignmentRequest(new BigDecimal("126250.000")));arrangeValidAssignment();service.assign(day.getId(),new OpenAssignmentRequest(attendant.getId(),meter.getId()));ArgumentCaptor<PumpShiftAssignment> c=ArgumentCaptor.forClass(PumpShiftAssignment.class);verify(shifts).saveAndFlush(c.capture());assertThat(c.getValue().getOpeningIndex()).isEqualByComparingTo("126250.000");}

 @Test void rejectsInactiveMeter(){arrangeValidAssignment();meter.setActive(false);assertThatThrownBy(()->service.assign(day.getId(),new OpenAssignmentRequest(attendant.getId(),meter.getId()))).isInstanceOf(BusinessException.class).hasMessageContaining("fuel meter");}
 @Test void closesDayWhenNoShiftIsOpen(){when(days.lockByIdAndOrganizationId(day.getId(),org.getId())).thenReturn(Optional.of(day));when(days.save(day)).thenReturn(day);assertThat(service.close(day.getId()).status()).isEqualTo(OperationalStatus.CLOSED);verify(history).save(any());}

 private void arrangeValidAssignment(){when(days.lockByIdAndOrganizationId(day.getId(),org.getId())).thenReturn(Optional.of(day));when(users.lockByIdAndOrganizationId(attendant.getId(),org.getId())).thenReturn(Optional.of(attendant));when(admin.existsByUserIdAndStationIdAndOrganizationIdAndValidUntilIsNull(attendant.getId(),station.getId(),org.getId())).thenReturn(true);when(meters.lockById(meter.getId())).thenReturn(Optional.of(meter));lenient().when(shifts.saveAndFlush(any())).thenAnswer(i->{PumpShiftAssignment a=i.getArgument(0);a.setId(UUID.randomUUID());return a;});}
 private PumpShiftAssignment openShift(){PumpShiftAssignment a=new PumpShiftAssignment();a.setId(UUID.randomUUID());a.setOperationalDay(day);a.setPumpAttendant(attendant);a.setFuelMeter(meter);a.setOpeningIndex(new BigDecimal("125000.000"));a.setStatus(OperationalStatus.OPEN);a.setOpenedBy(manager);a.setOpenedAt(OffsetDateTime.now());return a;}
 private User user(String code,boolean enabled){User u=new User();u.setId(UUID.randomUUID());u.setFirstName(code);u.setLastName("User");u.setOrganization(org);u.setEnabled(enabled);u.setRoles(Set.of(role(code)));return u;} private Role role(String code){Role r=new Role();r.setCode(code);r.setActive(true);return r;}
}
